### ISSUE TITLE
Payload may contain padding(=) when creating custom token.

### ISSUE THREAD

**Issue by IZAQI** [firebase/firebase-admin-python#107]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: CentOS 7.3
  * Firebase SDK version: 2.4 or 2.5
  * Firebase Product:  auth

### [REQUIRED] Step 3: Describe the problem

Firebase Product: auth

Payload may contain padding(=) when creating custom token.
Padding was not included in the node version even if the token was created using the same key.

It was possible to decode tokens containing padding created in python version with node version.
However, Json web token, which is one of the node's decoders, produces an error.
(https://github.com/auth0/node-jsonwebtoken)
Because it is defined as follows.
var JWS_REGEX = /^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$/;
(https://github.com/brianloveswords/node-jws/blob/master/lib/verify-stream.js)

Will this problem be fixed?
Should I look for another decoder?

-------
This sentence translated Japanese into English using Google Translate.

**Comment by hiranya911** [comment]
This is not likely to get fixed. Why are you even trying to decode custom tokens on your own? They are only meant to be passed along to the Firebase Auth servers via a `signInWithCustomToken()` call.

**Comment by IZAQI** [comment]
Thank you for your reply.

I understand that I can sign in by calling signInWithCustomToken ().
Currently avoiding errors by calling signInWithCustomToken ().
I asked
 a question to judge whether this error avoidance should be adopted as a formal process.

In my system, multiple databases work together with Firebase users as keys.
Therefore, I do not necessarily need to sign in to Firebase.
Since it is assumed that the load becomes instantaneously high, if only the target user is required in the REST API, I decode it myself.
Is it reasonable to sign in even in this situation?

------
This sentence translated Japanese into English using Google Translate.

**Comment by hiranya911** [comment]
It's very difficult to understand your specific question or use case from the translated description. In general, you should never mint a custom token, unless you're planning to sign in with it in a client-side app (Web, Android or IOS). That's all they are good for. If you just need to pass a uid to a client app, I'm sure there are other easier ways for that.

**Comment by LeonardoRick** [comment]
does this library have a `signInWithCustomToken()` vesion in python? I'm trying to connect a client python application

**Comment by hiranya911** [comment]
This library doesn't provide any client-side APIs at the moment.

**Comment by LeonardoRick** [comment]
@hiranya911 thanks. Any suggestion to achieve my goal?

**Comment by hiranya911** [comment]
You can try the REST API: https://firebase.google.com/docs/reference/rest/auth#section-verify-custom-token

Requires a web API key to access.
