### ISSUE TITLE
setup.py imports firebase_admin which requires six

### ISSUE THREAD

**Issue by carsongee** [firebase/firebase-admin-python#133]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.13
  * Firebase SDK version: 2.9.0
  * Library version: 2.9.0
  * Firebase Product: any

### [REQUIRED] Step 3: Describe the problem

If you don't already have python six installed, you can't install firebase

#### Steps to reproduce:

pip install .

#### Relevant Code:

setup.py has: `import firebase_admin` and `firebase_admin.__init__.py` has `import six` so if it isn't installed before installing the installation fails with:
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rh/fs2krkgj1hz_2ftgxgl20d980000gn/T/pip-mpnc1wob-build/setup.py", line 24, in <module>
        import firebase_admin
      File "/private/var/folders/rh/fs2krkgj1hz_2ftgxgl20d980000gn/T/pip-mpnc1wob-build/firebase_admin/__init__.py", line 21, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
```

**Comment by carsongee** [comment]
Also required for that `setup.py` to install from source are `google-auth` and `requests`

**Comment by hiranya911** [comment]
Install from source is a low priority for us. I think it's fair to ask developers to run `pip install -r requirements.txt` before attempting that.

**Comment by carsongee** [comment]
Fair enough, but at least this is here if someone else needs to install from the latest, a git tag, a fork ;), etc and this is just a dependency
