### ISSUE TITLE
FR: firestore-admin-java database/collections

### ISSUE THREAD

**Issue by chemelnucfin** [firebase/firebase-admin-python#135]
@hiranya911 I just realized that the collections I'm working on firestore-watch for python was copied from firestore-admin-java.  I'm working on the python versions now, but just in case there is similar python code that I'm not aware of from here.

Otherwise maybe I'll make a PR here when I'm done with them.
Thanks.

**Comment by hiranya911** [comment]
@chemelnucfin are you referring to the immutable collection types in the Java SDK? We haven't had a reason for using them in Python SDK yet (the database support here is simpler and based on the REST API).

**Comment by chemelnucfin** [comment]
ok!  thanks.
