### ISSUE TITLE
Validate Python 3 compatible syntax

### ISSUE THREAD

**Issue by ncouture** [firebase/firebase-admin-python#157]
There are at least some Python >= 3 invalid syntax used in this project (see print statements added in #130).

This suggests there is currently no such validation in place or the snippets are not validated to be compatible with Python >= 3.

**Comment by ncouture** [comment]
As a side note since this ticket discusses syntax validation;  I'm not sure what's the general rule of thumb when it comes to the Python syntax style used in their projects but as there a few inconsistencies with their style guide for instance `.pylintrc` defines line length to be of a maximum of 100 characters and [your style guide](https://google.github.io/styleguide/pyguide.html#Line_length ) prescribes 80 characters.

I would like to suggest using [yapf](https://github.com/google/yapf). For example the following yapf configuration makes it apply many changes based on Google's Python style guide:
```
[style]
based_on_style = google
```

**Comment by hiranya911** [comment]
We test the sources on both Python 2 and 3. The snippets have been upgraded to Python 3 syntax as of #157.
