### ISSUE TITLE
Firebase-  google-cloud-firestore error

### ISSUE THREAD

**Issue by constantinos07** [firebase/firebase-admin-python#179]
### Description of the problem
I am trying to run a Firestore request on the Google App Engine. When I execute the sample code below on an IDE, it runs without any errors. But when i execute it on the app engine: curl localhost:8080 I get the error message that is shown below.

### Description of the environment
pip version: 10.0.1
python:2.7.12

My requirements.txt file contains:
Flask==0.10
requests==2.18.4
requests-toolbelt==0.8.0
google-api-python-client
google-auth >= 1.3.0
google-cloud-firestore >= 0.27.0
google-cloud-storage >= 1.2.0

#### Log error:

ERROR    2018-07-07 13:01:57,240 wsgi.py:263] 
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHa
ndler
    handler, path, err = LoadObject(self._handler)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObje
ct
    obj = __import__(path[0])
  File "/home/ic/project/main.py", line 16, in <module>
    from firebase_admin import credentials,firestore
  File "/home/ic/project/lib/firebase_admin/firestore.py", line 28, in <module>
    raise ImportError('Failed to import the Cloud Firestore library for Python. Make sure '
ImportError: Failed to import the Cloud Firestore library for Python. Make sure to install the "google-cloud-firestore" module.

###sample code
import requests
import requests_toolbelt.adapters.appengine
import firebase_admin
from firebase_admin import credentials,firestore

requests_toolbelt.adapters.appengine.monkeypatch()
credentials = credentials.Certificate("key.json")
default_app = firebase_admin.initialize_app(credentials)

db= firestore.client()
    doc_ref = db.collection(u'docum1').document(u'name')
    doc_ref.set({u'name': u'name', })

**Comment by hiranya911** [comment]
If you're using the App Engine Flexible environment, one of the workaround mentioned in https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5023 should work for you. I have noticed that simply reinstalling `google-cloud-firestore` directly, also fixes the issue most of the time.

If you're using the App Engine Standard environment, Firestore Python client is not supported there.

**Comment by hiranya911** [comment]
@joelfernandes19 that's a question for the Firestore team. Check with https://github.com/GoogleCloudPlatform/google-cloud-python
