### ISSUE TITLE
ModuleNotFoundError: No module named 'google.auth'

### ISSUE THREAD

**Issue by FreakTheMighty** [firebase/firebase-admin-python#184]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: amazonlinux [Dockerfile](https://github.com/dix-icomys/bpy_lambda/blob/master/docker/Dockerfile) 
  * Firebase SDK version: v2.12.0
  * Library version: v2.12.0
  * Firebase Product: firestore

### [REQUIRED] Step 3: Describe the problem
pip install doesn't appear to install all transitive dependencies. As a result I'm getting missing module errors when I `from firebase_admin import firestore`

```
Traceback (most recent call last):
  File "lib/firebase_admin/firestore.py", line 22, in <module>
    from google.cloud import firestore # pylint: disable=import-error,no-name-in-module
  File "lib/google/cloud/firestore.py", line 18, in <module>
    from google.cloud.firestore_v1beta1 import __version__
  File "lib/google/cloud/firestore_v1beta1/__init__.py", line 20, in <module>
    from google.cloud.firestore_v1beta1 import types
  File "lib/google/cloud/firestore_v1beta1/types.py", line 18, in <module>
    from google.api_core.protobuf_helpers import get_messages
  File "lib/google/api_core/protobuf_helpers.py", line 21, in <module>
    from google.protobuf import field_mask_pb2
ModuleNotFoundError: No module named 'google.protobuf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from firebase_admin import firestore
  File "lib/firebase_admin/firestore.py", line 28, in <module>
    raise ImportError('Failed to import the Cloud Firestore library for Python. Make sure '
ImportError: Failed to import the Cloud Firestore library for Python. Make sure to install the "google-cloud-firestore" module.
```
#### Steps to reproduce:

I've created a dockerized reproduction of the problem:

1. git clone https://github.com/FreakTheMighty/FirestoreImportIssue.git
1. docker-compose run lambda bash test.sh
1. Note the traceback

#### Relevant Code:

```
from firebase_admin import firestore
```

**Comment by FreakTheMighty** [comment]
I see this is a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5023

**Comment by hiranya911** [comment]
The only working solution I've found for this problem is simply installing `google-cloud-firestore` directly -- in addition to `firebase-admin`. I'm going to see whether taking a dependency on `google-api-core[grpc]` is going to fix this (which is the resolution we got from the google-auth team), but they also recommended dropping direct dependencies on `requests` and `google-auth` which seems seems strange, and is the reason why I'm reluctant to implement the change.

**Comment by FreakTheMighty** [comment]
@hiranya911 I tried installing both directly, but couldn't get it to work. What versions do you pin google-cloud-firestore to? As you can see from my requirements.txt file above ☝️ I've locked firestore to `0.29.0`.

**Comment by Billcountry** [comment]
I'm experiencing the same issue. My packages are installed in the project directory `lib`.
The issue with exporting falls in when `firebase-admin` tries to import `google`.
If you have an installation of `google_appengine` the following module is imported instead:
```<module 'google' from '/usr/lib/google-cloud-sdk/platform/google_appengine/google/__init__.py'>```
while what we really expect is:
<module 'google.auth' from '/home/****/.local/lib/python2.7/site-packages/google/auth/__init__.pyc'>

**Comment by hiranya911** [comment]
@Billcountry you have a different problem stemming from the fact that Google Python libs use hierarchical packaging. See the discussion and the workarounds suggested in the following issue: https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/169

**Comment by hiranya911** [comment]
It seems installation of `grpcio` currently breaks on Pypy: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5902

We cannot implement the proposed fix until that gets resolved.

**Comment by hiranya911** [comment]
Now that #229 is in place, we might be able to revisit this.

**Comment by Dollysanskrut** [comment]
You will be having two libraries i.e one is global and other for your project locally. Go to terminal and type pip freeze and remove google auth library  (by copying the version )globally from the system, Now your local library will access google auth
