### ISSUE TITLE
Failed to initialize a certificate credential. Caused by: "No key could be detected."

### ISSUE THREAD

**Issue by tusharsoni08** [firebase/firebase-admin-python#188]
* Operating System version: Ubuntu 14 (Windows 10 Bash)
  * Firebase SDK version: 2.12.0
  * Firebase Product: database
  * Library: Python 2.7.15
I've installed Cloud Firestore Python library with following command:
pip install --upgrade firebase-admin

and I've used values of credentials of service account key in json format rather than giving file name, in environment variable as following way:
```
               cred = credentials.Certificate({
			  "type": "service_account",
			  "project_id": os.environ.get('PROJECT_ID'),
			  "private_key_id": os.environ.get('PRIVATE_KEY_ID'),
			  "private_key": os.environ.get('PRIVATE_KEY'),
			  "client_email": os.environ.get('CLIENT_EMAIL'),
			  "client_id": os.environ.get('CLIENT_ID'),
			  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
			  "token_uri": "https://accounts.google.com/o/oauth2/token",
			  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
			  "client_x509_cert_url": os.environ.get('CLIENT_CERT_URL')
		})

               default_app = firebase_admin.initialize_app(cred)
```
but it's showing error as follows:
          Failed to initialize a certificate credential. Caused by: "No key could be detected."

But when I use the string value as it is from service account key json without help of environment variable then it's working.
Please help me to resolve this issue.

**Comment by hiranya911** [comment]
Loading private key (which contains line terminators like `\n`) as an environment variable is tricky. Most shells would pad the terminator and treat it as a literal -- i.e. `\\n`. You will have to inspect how that value gets fed into your Python code, and preprocess/unpad accordingly. In my test environment I had to do the following:

```
"private_key": os.environ.get('PRIVATE_KEY').replace('\\n', '\n'),
```

**Comment by tusharsoni08** [comment]
Thanks a lot @hiranya911

**Comment by rahulj3716** [comment]
I am using the string value as it is from service account key JSON without the help of environment still it is showing the same error.
Please help its super urgent.

**Comment by brunomarks7** [comment]
Thanks a lot!
