### ISSUE TITLE
ImportError: No module named new

### ISSUE THREAD

**Issue by normmcgarry** [firebase/firebase-admin-python#200]
### [READ] Step 1: Are you in the right place?

Feels like a bug, unless it is specific to my machine somehow.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: OSX 10.13.6 - Python 2.7.15
  * Firebase SDK version: _____ (not sure the difference between this and library version)
  * Library version: 2.13.0
  * Firebase Product: Auth and Messaging

### [REQUIRED] Step 3: Describe the problem

When loading firebase-admin into an App Engine python project and running dev_appserver.py, I consistently receive the following error:

```
Error processing line 1 of /Repositories/project/lib/googleapis_common_protos-1.5.3-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  ImportError: No module named new

Remainder of file ignored
```

`googleapis_common_protos-1.5.3-py2.7-nspkg.pth` seems to be a dependency of Firebase Admin

#### Steps to reproduce:

Installed firebase admin.
`pip install -t lib -r requirements.txt`

In your `appengine_config.py`, include the lib folder:

```
from google.appengine.ext import vendor

# Add any libraries installed in the `lib` folder.
vendor.add('lib')
```

#### Relevant Code:

```
dev_appserver.py ./app.yaml
```

**Comment by hiranya911** [comment]
I can't repro the issue. Can you zip up your project and upload it so I can try with that? Don't include the lib directory -- just the requirements.txt file.

If you cannot share the project for some reason, provide a minimum, complete repro that we can test with.

**Comment by hiranya911** [comment]
Closing due to lack of follow up. Please reopen with more details if this problem continues to occur.
