### ISSUE TITLE
FR: arrayunion in update document (firestore)

### ISSUE THREAD

**Issue by irux** [firebase/firebase-admin-python#201]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: ??
  * Library version: 2.13.0
  * Firebase Product: Firestore (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem

I would like to do a array update in a collection and not replacing what it has and only join with the new value

#### Relevant Code:

```
db.collection("users").document(id).update({"myArray":["value to join"]})
```

**Comment by hiranya911** [comment]
This is supported in Node.js but not in Python. It will be added in a future release.

**Comment by raytso** [comment]
Any updates on this? It’s already in the tutorial docs.

**Comment by schmidt-sebastian** [comment]
CC @crwilcox

**Comment by busunkim96** [comment]
This has been supported since the v1beta1 release of the google-cloud-firestore.

https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array
https://googleapis.github.io/google-cloud-python/latest/firestore/transforms.html?highlight=arrayunion#module-google.cloud.firestore_v1beta1.transforms

**Comment by irux** [comment]
OK! it seems like this library doesn't support the new v1beta1 package and it imports the old firestore client. should we write a new issue for that feature ?

**Comment by busunkim96** [comment]
The library will default to v1, but you can import explicitly from v1beta1 to use this feature. 

```
from google.cloud import firestore
from google.cloud.firestore_v1beta1 import ArrayUnion

def update_doc_array():
    db = firestore.Client()
    # [START fs_update_doc_array]
    city_ref = db.collection(u'cities').document(u'DC')

    # Atomically add a new region to the 'regions' array field.
    city_ref.update({u'regions': ArrayUnion([u'greater_virginia'])})

    # // Atomically remove a region from the 'regions' array field.
    city_ref.update({u'regions': ArrayRemove([u'east_coast'])})
    # [END fs_update_doc_array]
    city = city_ref.get()
    print(u'Updated the regions field of the DC. {}'.format(city.to_dict()))
```

This is from the firestore [snippets.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets.py).

**Comment by hiranya911** [comment]
This should be supported now (at least since v3 release). Please let us know if you run into any problems.
