### ISSUE TITLE
FR: Add support for "webpush.fcm_options" (WebpushFcmOptions)

### ISSUE THREAD

**Issue by RoberMac** [firebase/firebase-admin-python#202]
As FCM HTTP API v1  and Firebase JS SDK already supports "[WebpushFcmOptions](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#WebpushFcmOptions)" and [click action handling](https://github.com/firebase/firebase-js-sdk/blob/master/packages/messaging/src/controllers/sw-controller.ts#L189) on Web , I forked this repo and will create a PR for this issue.

**Comment by hiranya911** [comment]
I'm on this one. Code being developed in a separate branch at the moment.

**Comment by hiranya911** [comment]
This was included in the 2.15.0 release.
