### ISSUE TITLE
Get information about app instances

### ISSUE THREAD

**Issue by JDeuce** [firebase/firebase-admin-python#204]
###  Describe your environment

  * Operating System version: Linux
  * Firebase SDK version: N/A
  * Library version: 2.13.0
  * Firebase Product: messaging (auth, database, storage, etc)

### Describe the problem

Firebase service API has app instance query API, to see which topics an instance id token is subscribed to, among other details. But this python library does not seem to have access to it. And so this is a feature request to add the other API call to the library

#### Relevant Docs;

https://developers.google.com/instance-id/reference/server#get_information_about_app_instances

**Comment by chong-shao** [comment]
Hi, we don't have plan to add this feature to the AdminSDK. 

In the future, IID Service will be replaced by a new API (Firebase Installation Service and Firebase Registration Service). But we don't have an estimated timeline now.
