### ISSUE TITLE
set merge doesnt work in Firestore

### ISSUE THREAD

**Issue by jchirik** [firebase/firebase-admin-python#205]
The docs refers to this format:
ref.document(upc).set(docData, merge=True)

This is the result I've been getting:
```
  File "db_manager.py", line 214, in uploadCSV
    ref.document(upc).set(docData, merge=True)
TypeError: set() got an unexpected keyword argument 'merge'
```

Everything else seems to work...

**Comment by kickerbear** [comment]
Hello, I see the same issue. Documentation repeatedly implies that using merge=True is the proper way to invoke merge sets. Please fix the documentation or the code.

**Comment by hiranya911** [comment]
Works fine for me. Just make sure the latest `google-cloud-firestore` dependency is installed. I believe the `mege` parameter was added in a recent release of Firestore.
