### ISSUE TITLE
Question: REST API's

### ISSUE THREAD

**Issue by akshaybabloo** [firebase/firebase-admin-python#208]
Will you be adding the new REST APIs to this library?

**Comment by hiranya911** [comment]
Which REST APIs are you referring to?

**Comment by akshaybabloo** [comment]
The one mentioned in https://firebase.google.com/docs/hosting/reference/rest/ and the others. Are they going to come in this package?

**Comment by hiranya911** [comment]
Not in the immediate future. But we'd like to expose Firebase Hosting APIs through the SDKs at some point. Right now we are working on adding the project management APIs to the Admin SDKs (#216).

You can certainly help speed things up by sending in pull requests for the APIs that you care about.
