### ISSUE TITLE
listen() function issue

### ISSUE THREAD

**Issue by yuanzhenxun** [firebase/firebase-admin-python#224]
Just a stupid question for reference.listen()
My code is:
def callback():
    print("hih")
    print("called")

if __name__ == '__main__':
    cred= credentials.Certificate("mykey.json")
    default_app=firebase_admin.initialize_app(cred,{'databaseURL' : myaddress})
    ref=db.reference()
    ll=ref.listen(callback())

Is this meaning every time when I change the data in my root direction, the callback function will be called? I tried but callback didn't be called when I change the data from console.

Please tell me did I use listen function wrong?

**Comment by hiranya911** [comment]
`callback` should take an argument. Please use Stackoverflow for this type of usage questions.
