### ISSUE TITLE
Long running daemon getting stuck in push

### ISSUE THREAD

**Issue by seblucas** [firebase/firebase-admin-python#233]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Alpine Linux 3.8.1
  * Firebase SDK version: 2.14.0 (also tried 2.13.0)
  * Library version: ? How do I get that
  * Firebase Product: database

#### Steps to reproduce:

I use Firebase realtime database to store data coming from sensor (temperature, humidity, ...) around my home. So I have program listening to MQTT topic and storing data with Firebase Admin SDK.

The problem I have is that it works fine for a while but after some time (2 to 12 hours) it will get stuck on a firebase `push`.

What I mean by stuck is that I can see the log string before the push and nothing after, no Exception is thrown, it is stuck.

In case that's interesting before switching to Admin SDK, I was using the REST Api with the old API Key and it worked for months 24/7 not missing a single message. I did not find a way to generate an oauth token with a long lifespan (a year or so) so I had to use Admin SDK.

I don't know how to debug it further. I can share the link to my Firebase project if needed. Is Admin SDK built to be run for a long time (several months 24/7) ? Should I only use Admin SDK to generate OAuth token and use the REST API (that would mean ~300 new token each day) ?

#### Relevant Code:

The full code is here : https://github.com/seblucas/mqtt2firebase/blob/master/mqtt2firebase.py

I also tried without having a specific thread for Firebase (check the history if needed)

It get stuck on this line : https://github.com/seblucas/mqtt2firebase/blob/6446db971ce162cdaee1d8ceffec93ab6238504b/mqtt2firebase.py#L57

**Comment by seblucas** [comment]
For information I tried dropping Admin SDK and replaced it by using the REST Api as shown [there](https://firebase.google.com/docs/database/rest/auth) and it's been running for 3 hours without any problems. I'm hoping it get through the night (that would be a first since dropping the REST Api with the Old API Key)

**Comment by hiranya911** [comment]
Hi @seblucas. Admin SDK calls the REST API under the hood too -- using `requests` to make the HTTP call, and `google-auth` for handling authorization. The `push()` method simply does an HTTP POST:

https://github.com/firebase/firebase-admin-python/blob/932cf17a6f222c627dbd1502658f3eb338077250/firebase_admin/db.py#L319-L321

I will try to start a long running test using a modified version of your code, and see if it can be reproduced. But I've used the SDK in the past in experiments that lasted for many days (in multiple environments like local machine, App Engine and Compute Engine).

1. Can you describe your environment a bit?
2. When this happens, does your process exit?
3. If not, seeing as you're using a separate thread, does the thread die (not sure how or why, but can possibly explain the observation)?

**Comment by seblucas** [comment]
First thanks for your answer.

Indeed as you said I have the same problem with the REST API ...

I've added a timeout and restarted it to see if that helps or not.

About my environment : 
 * the alpine linux I was talking about is a docker (18.06.1-ce) container running on a Raspberry Pi 2 (armhf).
 * IPV6 is enabled on Raspberry Pi (in case that's interesting for you)
 * I'm using python 3.6.6

With or without thread the process was stuck -> no exit, I have to kill the container / restart it.

I've not checked if the thread dies, will add a check about that

**Comment by hiranya911** [comment]
@seblucas if this happened with the REST API as well, it's most likely a low-level networking issue. Setting a timeout should help the process get unstuck in that case (by default `requests` connections don't timeout). When using the SDK, you can pass the `httpTimeout` option to the `initialize_app()` call:

https://github.com/firebase/firebase-admin-python/blob/932cf17a6f222c627dbd1502658f3eb338077250/firebase_admin/__init__.py#L52-L55

And this is from the [`requests` documentation](http://docs.python-requests.org/en/master/user/quickstart/#timeouts):

> You can tell Requests to stop waiting for a response after a given number of seconds with the timeout parameter. Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely:

**Comment by seblucas** [comment]
That's exactly what I'm trying right now (With Rest Api). So far no problem.

If that seems to work, I'll test again with Admin SDK. Thanks for the snippet ;).

**Comment by seblucas** [comment]
So even after adding a timeout, I still had some problems yesterday. 

But so far it's been 21 hours without any problem. As you said in your first answer, I think there was some problem in low level networking during the weekend and my ISP may have fixed it. At least I hope so.

I'll close it as it does not seem to be a bug. Sorry for opening this issue but thanks a lot to @hiranya911  for taking the time to troubleshoot it with me ;).
