### ISSUE TITLE
Firebase storage not working 

### ISSUE THREAD

**Issue by alexanderwhatley** [firebase/firebase-admin-python#235]
Operating System: Ubuntu 18.04
Firebase SDK Version: 2.14.0

I am trying a very simple task, namely to list out the blobs in a bucket. 'Samples' is an existing bucket, which I can very clearly see on the firebase storage UI. I have the following code, which results in an error message:

```
from firebase_admin import credentials, storage
from firebase_admin import db as firebase_db

cert = credentials.Certificate(...)
firebase_admin.initialize_app(
            cert,
            {'databaseURL': ...,
            'storageBucket': ...)
bucket = storage.bucket('Samples')
bucket.list_blobs()
```
I then get:
```
---------------------------------------------------------------------------
NotFound                                  Traceback (most recent call last)
<ipython-input-4-fb874cadc115> in <module>()
----> 1 list(bucket.list_blobs())

~/anaconda3/lib/python3.7/site-packages/google/api_core/page_iterator.py in _items_iter(self)
    197     def _items_iter(self):
    198         """Iterator for each item returned."""
--> 199         for page in self._page_iter(increment=False):
    200             for item in page:
    201                 self.num_results += 1

~/anaconda3/lib/python3.7/site-packages/google/api_core/page_iterator.py in _page_iter(self, increment)
    228             Page: each page of items from the API.
    229         """
--> 230         page = self._next_page()
    231         while page is not None:
    232             self.page_number += 1

~/anaconda3/lib/python3.7/site-packages/google/api_core/page_iterator.py in _next_page(self)
    347         """
    348         if self._has_next_page():
--> 349             response = self._get_next_page_response()
    350             items = response.get(self._items_key, ())
    351             page = Page(self, items, self.item_to_value)

~/anaconda3/lib/python3.7/site-packages/google/api_core/page_iterator.py in _get_next_page_response(self)
    399                 method=self._HTTP_METHOD,
    400                 path=self.path,
--> 401                 query_params=params)
    402         elif self._HTTP_METHOD == 'POST':
    403             return self.api_request(

~/anaconda3/lib/python3.7/site-packages/google/cloud/_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object)
    291 
    292         if not 200 <= response.status_code < 300:
--> 293             raise exceptions.from_http_response(response)
    294 
    295         if expect_json and response.content:

NotFound: 404 GET https://www.googleapis.com/storage/v1/b/Samples/o?projection=noAcl: Not Found
```
Moreover, testing if the bucket even exists results in an error as well:
`bucket.exists()`
```
---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
<ipython-input-6-87ca7eb6e38b> in <module>()
----> 1 bucket.exists()

~/anaconda3/lib/python3.7/site-packages/google/cloud/storage/bucket.py in exists(self, client)
    421             client._connection.api_request(
    422                 method='GET', path=self.path,
--> 423                 query_params=query_params, _target_object=None)
    424             # NOTE: This will not fail immediately in a batch. However, when
    425             #       Batch.finish() is called, the resulting `NotFound` will be

~/anaconda3/lib/python3.7/site-packages/google/cloud/_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object)
    291 
    292         if not 200 <= response.status_code < 300:
--> 293             raise exceptions.from_http_response(response)
    294 
    295         if expect_json and response.content:

BadRequest: 400 GET https://www.googleapis.com/storage/v1/b/Samples?fields=name: Invalid bucket name: 'Samples'
```

**Comment by hiranya911** [comment]
Is you bucket name correct, and does the specified service account have permissions over it? "Samples" doesn't sound like a correct bucket name. Buckets provisioned by Firebase usually have the name format: `<project-id>.appspot.com`.

**Comment by alexanderwhatley** [comment]
@hiranya911 , I just repeated it with the default bucket, and got the same error:

In [2]: bucket = storage.bucket()

In [3]: bucket
Out[3]: <Bucket: gs://<project-id>.appspot.com>

In [4]: list(bucket.list_blobs())
---------------------------------------------------------------------------
NotFound                                  Traceback (most recent call last)
<ipython-input-4-fb874cadc115> in <module>()
----> 1 list(bucket.list_blobs())

~/anaconda3/lib/python3.7/site-packages/google/api_core/page_iterator.py in _items_iter(self)
    197     def _items_iter(self):
    198         """Iterator for each item returned."""
--> 199         for page in self._page_iter(increment=False):
    200             for item in page:
    201                 self.num_results += 1

~/anaconda3/lib/python3.7/site-packages/google/api_core/page_iterator.py in _page_iter(self, increment)
    228             Page: each page of items from the API.
    229         """
--> 230         page = self._next_page()
    231         while page is not None:
    232             self.page_number += 1

~/anaconda3/lib/python3.7/site-packages/google/api_core/page_iterator.py in _next_page(self)
    347         """
    348         if self._has_next_page():
--> 349             response = self._get_next_page_response()
    350             items = response.get(self._items_key, ())
    351             page = Page(self, items, self.item_to_value)

~/anaconda3/lib/python3.7/site-packages/google/api_core/page_iterator.py in _get_next_page_response(self)
    399                 method=self._HTTP_METHOD,
    400                 path=self.path,
--> 401                 query_params=params)
    402         elif self._HTTP_METHOD == 'POST':
    403             return self.api_request(

~/anaconda3/lib/python3.7/site-packages/google/cloud/_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object)
    291 
    292         if not 200 <= response.status_code < 300:
--> 293             raise exceptions.from_http_response(response)
    294 
    295         if expect_json and response.content:

NotFound: 404 GET https://www.googleapis.com/storage/v1/b/gs://<project-id>.appspot.com/o?projection=noAcl: Not Found

**Comment by hiranya911** [comment]
Both operations work fine for me.

```
ops = {       
        'storageBucket' : '{0}.appspot.com'.format(project_id)
}
firebase_admin.initialize_app(cred, ops)

bucket = storage.bucket()
print(bucket.list_blobs())
print(bucket.exists())
```

**Comment by hiranya911** [comment]
Your bucket name is still not specified correctly. The error indicates: `gs://<project-id>.appspot.com`, which is wrong.

**Comment by alexanderwhatley** [comment]
Ah that was the problem, once I changed it to <project-id>.appspot.com, it worked! Thanks.
