### ISSUE TITLE
'document.set' fails with python-rq

### ISSUE THREAD

**Issue by Kcrong** [firebase/firebase-admin-python#244]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

**OS X Mojave 10.14.2**
- python == 3.6.6
- rq==0.13.0
- rq-dashboard==0.3.12
- rq-scheduler==0.9
- firebase-admin==2.14.0
- google-cloud-firestore==0.31.0

##### worker.py

```python
#!/usr/bin/env python
import random
import string
import sys
import logging

from redis import Redis
from rq import Connection, Worker

def randomkey(length):
    return ''.join(random.choice(string.ascii_lowercase) for _ in range(length))

logging.getLogger('rq.worker').propagate = False

logger = logging.getLogger("matching.queue")
logger.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(formatter)

file_handler = logging.FileHandler('worker-{}.log'.format(sys.argv[1] or randomkey(10)), encoding='utf8')
file_handler.setFormatter(formatter)

logger.addHandler(stream_handler)
logger.addHandler(file_handler)

with Connection(connection=Redis(host=current_config.REDIS_HOST, port=current_config.REDIS_PORT)):
    Worker(['default']).work()
```

##### rq_queue.py

```python
from firebase_admin import firestore

def queue():
    firestore.client().collection('collection_name').document('1').set({'id': 1})
```

##### rq_firebase.py

```python
from rq_queue import queue


def main():
    from app.config import current_config
    from datetime import datetime
    from rq_scheduler import Scheduler
    from redis import Redis
    import firebase_admin
    from firebase_admin import credentials

    config = current_config

    cred = credentials.Certificate(config.FIREBASE_KEY_FILE)
    firebase_admin.initialize_app(cred)

    scheduler = Scheduler(connection=Redis(host=config.REDIS_HOST, port=config.REDIS_PORT))

    # Start matching
    scheduler.enqueue_job(scheduler.schedule(
        scheduled_time=datetime.utcnow(),  # Time for first execution, in UTC timezone
        func=queue,  # Function to be queued
        args=[],  # Arguments passed into function when executed
        kwargs={},  # Keyword arguments passed into function when executed
        interval=10,  # Time before the function is called again, in seconds
        repeat=None  # Repeat this number of times (None means repeat forever)
    ))


if __name__ == '__main__':
    main()
```

##### Terminal 1
```bash
$ python worker1.py
```

##### Terminal 2
```bash
$ python rq_firebase.py
```

#### Stack trace
```
15:12:50 RQ worker 'rq:worker:Kcrong-MacBook-Pro.77452' started, version 0.13.0
15:12:50 *** Listening on default...
15:12:50 Cleaning registries for queue: default
15:13:01 default: rq_queue.queue() (dc63be8d-42f6-4d02-ae06-72559ada54fb)
15:13:02 Moving job to 'failed' queue (work-horse terminated unexpectedly; waitpid returned 11)
15:13:04 Warm shut down requested
```

**Comment by hiranya911** [comment]
We are not familiar with RQ, but according to http://python-rq.org/docs/workers/ the worker runs the function as a separate child process. Therefore you have to initialize the Admin SDK in the context of your `queue` function. You can't init the SDK in the `rq_firebase.py` process, and access Firestore in another process. 

If you add some error handling logic to your function, the exact problem should become clear.

**Comment by Kcrong** [comment]
@hiranya911 Thanks for the answer. But I tried to initialize the Admin SDK inside of the queue function, it still has the same error. 
I think it doesn't matter where I import the initialized app. 

This is the code that I initialized the Admin SDK.

##### rq_queue.py
```python
import firebase_admin
from firebase_admin import firestore, credentials

def queue():
    cred = credentials.Certificate(current_config.FIREBASE_KEY_FILE)
    firebase_admin.initialize_app(cred, name='asdfasdf')
    firestore.client().collection('matches').document(str(1)).set({'id': 1})
```

And I double checked there is `matches` collection, document named by '1' in my storage.

**Comment by hiranya911** [comment]
There are at least 2 errors in the above code:

1. `current_config` variable is not in scope.
2. You are giving your app a name. Therefore you must pass the app instance to the `firestore.client()` method.

I think you should try to run the above function directly (without rq), and see what happens. If you can reproduce any unusual errors that way, then we can take a look. Otherwise, there's not much we can do, and you should reach out to the rq community for assistance.

**Comment by Kcrong** [comment]
1. Without rq, it runs perfectly I expected. 
2. `current_config` is just fake variable. I just wanted to mentioned that I passed valid FIREBASE_KEY_FILE. 
3. After initialized, do I still need to pass the app instance to the `firestore.client()`? 

I got it what you say. I'll move to the rq community, and get some help. 

Thanks.

**Comment by hiranya911** [comment]
If you name your app, then you must pass the app to `firestore.client()`.
