### ISSUE TITLE
FR - support older version of `requests`

### ISSUE THREAD

**Issue by ipande** [firebase/firebase-admin-python#257]
* Operating System version: python 2.7.15
  * Firebase SDK version: ??
  * Library version: ??
  * Firebase Product: messaging

Step 3: Unable to import firebase_admin.messaging

```
In [4]: from firebase_admin import messaging
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-0c6dddb1c046> in <module>()
----> 1 from firebase_admin import messaging

/postmates/virtualenv.d/postal-main/lib/python2.7/site-packages/firebase_admin/messaging.py in <module>()
     18 import six
     19 
---> 20 from firebase_admin import _http_client
     21 from firebase_admin import _messaging_utils
     22 from firebase_admin import _utils

/postmates/virtualenv.d/postal-main/lib/python2.7/site-packages/firebase_admin/_http_client.py in <module>()
     20 from google.auth import transport
     21 import requests
---> 22 from requests.packages.urllib3.util import retry # pylint: disable=import-error
     23 
     24 
```

The version of requests we're using is `requests==2.2.1`

**Comment by hiranya911** [comment]
We get our `requests` dependency through `google-api-core` and other upstream dependencies. They require at least requests v2.18.0 at the moment: 

https://github.com/googleapis/google-cloud-python/blob/1f15fe411ebd1f1cd664599920fc4962b01a8a06/api_core/setup.py#L35

requests v2.2.1 is over 5 years old. Please consider upgrading to something more recent.
