### ISSUE TITLE
Not possible to initialise using service account ID without credential file

### ISSUE THREAD

**Issue by binishkaspar** [firebase/firebase-admin-python#259]
Its not possible to initialise using service account ID without credential file

Based on [Create Custom Token document](https://firebase.google.com/docs/auth/admin/create-custom-tokens?authuser=0) it should be possible to initialise the app using service account ID as below,

```
options = {
    'serviceAccountId': 'my-client-id@my-project-id.iam.gserviceaccount.com',
}
firebase_admin.initialize_app(options=options)
```

But the above code doesn't work, with appropriate serviceAccountID and iAm Role.

**Comment by hiranya911** [comment]
Works fine as far as I can tell. You need to provide more details like error messages, stack traces etc.

**Comment by hiranya911** [comment]
I'm going to close this due to lack of follow up/details. Please reopen with more info if this needs to be looked at.
