### ISSUE TITLE
Listener automatically fires every hour, even without database changes

### ISSUE THREAD

**Issue by charliesneath** [firebase/firebase-admin-python#267]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux raspberrypi 4.14.79+ #1159 Sun Nov 4 17:28:08 GMT 2018 armv6l GNU/Linux
  * Firebase SDK version: 2.15.1
  * Library version: _____ (not sure how to find, will add if I do)
  * Firebase Product: database

### [REQUIRED] Step 3: Describe the problem

If I setup a new reference listener using the listen() method, the listener will automatically fire each hour, even if there are no changes to the database. I only expect the listener to fire when there are changes at the database reference path

I originally reported this issue to the Firebase support team, and this is the response they provided:

> Apparently, the listen() method of the Admin SDK for Python is an experimental feature. Given the nature of the error and that this is using the streaming REST API under the hood, it is likely that access tokens expire every hour and the HTTP connection has to be refreshed with a new token.

#### Steps to reproduce:

Set up a new reference listener using `firebase_admin.db.reference(loc_path).listen(db)` and monitor output. Listener will fire every hour after it was originally started, even if there are no changes in the database.

See this screenshot for sample output: 

<img width="699" alt="image" src="https://user-images.githubusercontent.com/606854/53809587-0e6de880-3f23-11e9-8ee1-445bcd760bb9.png">

#### Relevant Code:

```
# Firebase modules
import os
import datetime
import firebase_admin
from firebase_admin import db
from firebase_admin import credentials

# Init Firebase.
dir_path = os.path.dirname(os.path.realpath(__file__))
cred = credentials.Certificate(dir_path + '/serviceAccountKey.json')
firebase_admin.initialize_app(cred, {
    'databaseURL': DB_URL
})


def db(event):
    print('Firebase event detected: ')
    print('Path: ' + event.path)
    print('Data: ' + event.data)
    print('Event type: ' + event.event_type)

    now = datetime.datetime.now()
    human_timestamp = '{y}-{mon}-{d} {h}:{min}:{s}'.format(
        y=now.year,
        mon=now.month,
        d=now.day,
        h=now.hour,
        min=now.minute,
        s=now.second
    )

    print(human_timestamp)


if __name__ == "__main__":
    loc_path = 'test/key'
    listener = firebase_admin.db.reference(loc_path).listen(db)

    try:
        while True:
            pass
    except KeyboardInterrupt:
        listener.close()
```

**Comment by hiranya911** [comment]
As stated in the response from the support team, this is because of the hourly token expiration. The SDK must reconnect whenever this happens, which results in a new event being injected. 

Since the Python SDK does not keep a local cache of all the events/data received from the server, this is the best it can do. We expect the client code to cache the data handle duplicates accordingly if this is a problem. That and other than documenting this behavior, I don't think there's anything that can be done to resolve this.

**Comment by rawmean** [comment]
My client code can handle the duplicates but the problem is that my firebase account is being billed for all these hourly updates and that has increased my firebase cost significantly.

Can you please help?

**Comment by hiranya911** [comment]
@rawmean see my comment on #275. Unfortunately there's no simple fix for this problem.

> One possible solution is to not call the "callback" function with the entire database every time it connects and leave it to the client to to ask for the entire database.

This requires changing how the RTDB servers work today. Existing behavior is to return all the contents of the current node, whenever a client establishes a new connection. Even if we somehow manage to implement this change, it's still not going to be good enough. The database contents may have changed while the SDK was reconnecting, and the server has to also signal the client of these changes. Implementing all this is going to be a massive undertaking in both the server and client (SDK) sides.

> Alternatively, is it possible to increase the token timeout time?

No. OAuth2 tokens are produced by Google auth servers, and the tokens have a TTL of 1 hour for security reasons.

**Comment by rawmean** [comment]
@hiranya911 

I just saw this recent blog from firebase which says it is possible to set expiration to a custom value, but I can't figure out how to do this (https://firebase.googleblog.com/2018/04/whats-new-in-firebase-authentication.html):
`With this release, we introduce the capability to issue JWT-based session cookies from the Firebase Admin SDK. This will allow you to create session cookies with custom expiration times ranging from 5 minutes to 2 weeks and still retain all the benefits of custom claims client-side to provide logic and customization to your application.

We've got more details as well as samples of our session management capabilities available in our Admin SDK docs.`

**Comment by hiranya911** [comment]
Session cookies are a whole different beast: https://firebase.google.com/docs/auth/admin/manage-cookies

They cannot be used to access Realtime Database.

**Comment by rawmean** [comment]
@hiranya911 ok, based on one of your suggestions, I implemented a CloudFunction and have it trigger on `.write` (which means any change). I tested it on a small test database to make sure it works. (your article on Medium was very helpful)

**Problem**: On the real database which has ~6k items, I get a TRIGGER_PAYLOAD_TOO_LARGE error every time I try to change an item in the database. I suspect this is because firebase sends the entire database to the CF every time a small change to the database occurs. So, installing the CF locks up the database.

Suggestion? Remember that the CF was created to avoid the problem with '.listen' which disconnects every hour and causes the entire db to be dumped.

**Comment by hiranya911** [comment]
Hi @rawmean. You will need to re-org/denormalize your database so your update payloads become small. I assume that each write only modifies a small portion of your database. You will need to isolate these parts, and configure your function to listen to only those nodes. If you can share your database schema, and point out the portions that get updated, I can try to provide a more concrete solution.

**Comment by rawmean** [comment]
Thanks. This is how my DB is organized.
`e_tokens` is where clients upload small pieces of data (tokens), but there are a lot of them. The data does not change very frequently either. The same is true for other branches: the updates are small by there are a lot of entries.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/1287087/55371570-85ab8380-54b3-11e9-9d51-6bffab6b5d7e.png">

**Comment by hiranya911** [comment]
Thanks. I assume there's more nesting under `e_tokens`. Perhaps one child node for each client? 

```
e_tokens
   `--- client1
   |         `--- key1: val1
   |          `--- key2: val2
   `--- client2
             `--- key1: val1
             `--- key2: val2
```

If so I would start by configuring the cloud function to listen on something like `/e_tokens/{clientId}`.

```
--trigger-resource projects/_/instances/your-project-id/refs/e_tokens/{clientId}
```

Now when a client updates their token information, each function will only receive a small payload corresponding to that clients `e_tokens/client_id` node. Does that sound like a viable option for your application?

**Comment by rawmean** [comment]
1.  You are correct about the scheme. It's exactly how you showed it (sorry, I should have expanded it)
2. Your suggestion (wildcard) worked perfectly
3. You are a genius and super-helpful. Thank you!

So, I am going to do the following next. Can you please let me know if it makes sense or if there is a better way?

- CloudFunction (CF) will be triggered every time the DB under the `e_tokens` path changes (using the wildcard path, of course)
- CF then writes the delta on a separate branch of the tree which I call `tgauge/listen/e_tokens`. This branch is small because it only contains deltas.
- My python code which I run on my local server listens (using the python firebase `.listen` API) on `tgauge/listen/e_tokens` (which is small) and acts on it. It then removes the entries that it has acted on. 

In this way, I have avoided the problem that I had with big unnecessary dumps of (due to oAuth token expiration and reconnecting every hour).

It's quite a bit of gymnastics and somewhat ugly, but that's the best thing that I have come up with so far. Your input is highly appreciated.

**Comment by hiranya911** [comment]
> My python code which I run on my local server listens (using the python firebase .listen API) on tgauge/listen/e_tokens (which is small) and acts on it. It then removes the entries that it has acted on.

Why not simply implement all your logic in the Cloud Function? I'd make that a priority, and completely eliminate the server that's listening for realtime updates. That way your architecture is very clean and easy to reason about. Any reason this is not an option?

**Comment by rawmean** [comment]
The problem with the CF-only approach is that my server does some heavy scheduling work (e.g., monitors the state of each client periodically and acts on their behalf). The server function is stateful as a result and CF is designed to be stateless and short-lived (if I understood it correctly)

**Comment by hiranya911** [comment]
Yes CF is stateless. Perhaps you can try to save the state of your application in the database, and query that information from CF when needed. If you have any logic that needs to be executed periodically, you can put it in a 2nd CF, and have it be triggered periodically: https://cloud.google.com/scheduler/docs/tut-pub-sub

If none of these options are feasible for you, what you've suggested above should work. But I'd only do it as a last resort, after ruling out all the serverless options.

**Comment by rawmean** [comment]
@hiranya911 I encountered another problem. I'm hoping you can help. Consider the following example and suppose the client changes `key2:val2` under `client1`:
`
e_tokens
   `--- client1
   |         `--- key1: val1
   |         `--- key2: val2
   `--- client2
             `--- key1: val1
             `--- key2: val2
`

The [documentation](https://firebase.google.com/docs/functions/database-events) says that:
" For onWrite or onUpdate events, the first parameter is a Change object that contains two snapshots that represent the data state before and *after* the triggering event".

However, the CloudFunction (CF) only gets `key2:val2` as 'delta' and what's under `client1` *prior* to the change. CF does not get the data *after* the change as specified in the document (which is what I need).

The CF is installed as follows per your instructions above.
`gcloud beta functions deploy climate_rtdb --runtime python37 --trigger-event=providers/google.firebase.database/eventTypes/ref.write --trigger-resource=projects/_/instances/xyz-abf59/refs/e_token/{clientId}
`

Thanks for all your help.
