### ISSUE TITLE
HttpTimeout Option does not seem to be working

### ISSUE THREAD

**Issue by chonigman** [firebase/firebase-admin-python#270]
Hi, 

I'm trying to set the timeout option for my database calls. However, it does not appear that it is working (failed reads hang indefinitely). 

OS: Windows 10
Python 3.6.8
firebase-admin 2.15.1
google-cloud-firestore 0.31.0

Perhaps I'm not understanding how this is supposed to work. I get my db instance from google-cloud-firestore pacakge but authorize my app through the firebase-admin. I set the httpTimeout option in my initializeApp, which I assume is in seconds and should be a number. 

Thanks

**Comment by hiranya911** [comment]
`httpTimeout` only applies to clients that use REST. That mainly includes `db` and `messaging` modules at the moment. Firestore uses a different communication medium (grpc), and doesn't support our `httpTimeout` setting.
