### ISSUE TITLE
FR: add FieldValue.increment() feature in Firestore

### ISSUE THREAD

**Issue by A-Iskakov** [firebase/firebase-admin-python#271]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: ubuntu 18.04
  * Firebase SDK version: v2.16.0
  * Library version: python3.6
  * Firebase Product: firebase

### [REQUIRED] Step 3: Describe the problem

Hello,
I have noticed new feature FieldValue.increment() in the latest SDK for [JavaScript](https://firebase.google.com/support/release-notes/js) 
is it possible to add this feature in Python SDK?
Many thanks!

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by A-Iskakov** [comment]
should I addess this feature [here](https://github.com/googleapis/google-cloud-python/tree/master/firestore)?

**Comment by hiranya911** [comment]
Hi @A-Iskakov. Yes, please report at https://github.com/googleapis/google-cloud-python where the Firestore client resides.

**Comment by A-Iskakov** [comment]
Duplicate of #[7533](https://github.com/googleapis/google-cloud-python/issues/7533)
