### ISSUE TITLE
FR: getting Usage over time statistics from Admin SDK

### ISSUE THREAD

**Issue by A-Iskakov** [firebase/firebase-admin-python#272]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: ubuntu 18.04
  * Firebase SDK version: v2.16.0
  * Library version: python3.6
  * Firebase Product: firebase

### [REQUIRED] Step 3: Describe the problem

Hello,
is it possible to add feature of getting Firebase Firestore Usage Statictics which can be gathered only from Firebase web console?

![image](https://user-images.githubusercontent.com/26543542/54479073-5950ff80-4843-11e9-8acf-65be738e4605.png)

Many thanks!

**Comment by hiranya911** [comment]
I've filed a feature request to the console team. They will follow up soon.

**Comment by jmourits** [comment]
You should be able to get the same data via StackDriver.  You can play with the UI and metrics here: https://app.google.stackdriver.com/metrics-explorer?project=<your project id>

You should be able to get access to the data via API as well following these instructions:
https://cloud.google.com/monitoring/api/v3/

**Comment by A-Iskakov** [comment]
@jmourits hello, thanks for the information
Is it possible to get metrics from Stackdriver API using [python client ](https://googleapis.github.io/google-cloud-python/latest/monitoring/index.html)? As noticed there are only names of descriptors I could get using it.

**Comment by hiranya911** [comment]
It does support other operations as far as I can tell: https://googleapis.github.io/google-cloud-python/latest/monitoring/query.html

Please check with the community at https://github.com/googleapis/google-cloud-python for any follow ups.
