### ISSUE TITLE
auth.generate_sign_in_with_email_link Workflow

### ISSUE THREAD

**Issue by marban** [firebase/firebase-admin-python#273]
Can someone point me to an example for the workflow after auth.generate_sign_in_with_email_link() on the server-side?
I get forwarded to http://myapp.com/verify?apiKey=1&oobCode=2&mode=signIn&lang=en
but how can I generate a valid token for auth.verify_id_token() from the oobCode & mode?

I guess the Web equivalent would be firebase.auth().signInWithEmailLink(email, window.location.href)

**Comment by hiranya911** [comment]
There's no such workflow. These links are intended to be emailed to clients, where they  can be used in conjunction with a client SDK.
