### ISSUE TITLE
FR: handle more than 100 messages in send_all

### ISSUE THREAD

**Issue by vwvw** [firebase/firebase-admin-python#286]
* Firebase Product: messaging

After the merging of #283 I was wondering why the limit of 100 messages per call was chosen and if you would be interested in offering a method that would automatically split the list of messages if there are more than 100 and submit a call for each group.

**Comment by chong-shao** [comment]
Hi vwvw, we are working on increasing the limit but currently I don't have the estimate timeline for this.

**Comment by vwvw** [comment]
Thanks for the info!
