### ISSUE TITLE
FR: Add bandit security static analysis scanner

### ISSUE THREAD

**Issue by c-goosen** [firebase/firebase-admin-python#299]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Pop!_OS 19.04 (ubuntu)
  * Firebase SDK version: 2.17.0
  * Library version: 2.17.0
  * Firebase Product: auth,database, etc.

### [REQUIRED] Step 3: Describe the problem
Prevent security issues.

#### Relevant Code:

```
tox.ini updated
.travis.yml updated
```

**Comment by hiranya911** [comment]
Closing as won't fix.
