### ISSUE TITLE
How to pass options in initialize_app

### ISSUE THREAD

**Issue by PatriceBertrand** [firebase/firebase-admin-python#30]
initialize_app has an options= argument, and I found this [documented for Java here](https://firebase.google.com/docs/database/admin/start), but cannot get it working in Python.

This is what I have tried for the DataBaseAuthVariableOverride option: 

`current_app.firebase_app = initialize_app(cred, options={'DatabaseAuthVariableOverride': {'uid': 'my-uid'}})`

**Comment by hiranya911** [comment]
Options are not supported in the Python Admin SDK yet. You can pass them to `initialize_app()`, but the SDK currently doesn't do anything with them since we don't have a database API yet for Python. What exactly are you trying to achieve?

**Comment by PatriceBertrand** [comment]
Thank you for your answer.  What I am trying to do is to authenticate with limited privilege, [as recommended in the official docs](https://firebase.google.com/docs/auth/admin/#create_a_custom_token).

> Note: If you just need to connect to the Firebase Realtime Database from your own server, don't use custom tokens. Instead, use a Firebase Admin SDK to authenticate with limited privileges.

So my idea was to authenticate with DatabaseAuthVariableOverride and a uid, so as to be under the control of the .write rules.    But maybe this is an extreme consideration.

It seems the Java admin lib does offer this option.

**Comment by hiranya911** [comment]
Yes, Java Admin SDK supports it. Python Admin SDK does not support real time database access as of yet. There's some work in progress to enable that (see #28).

**Comment by hiranya911** [comment]
Database support has been released now: https://firebase.google.com/support/release-notes/admin/python#2.1.0

**Comment by LeonardoRick** [comment]
What about Firestore support? Can I authenticate a user with limited privilege for this specific service?

**Comment by hiranya911** [comment]
Firestore server libraries do not offer a limited privilege mode: https://firebase.google.com/docs/firestore/security/overview
