### ISSUE TITLE
Firebase keep producing noisy log

### ISSUE THREAD

**Issue by b3g00d** [firebase/firebase-admin-python#305]
* Operating System version: Ubuntu 18.04
  * Library version: 2.17.0
  * Firebase Product: notify

Firebase messaging send_all keep producing this log

```
__init__() takes at most 1 positional argument (3 given)                            
Attempting refresh to obtain initial access_token                        
```
And I can only remove the first log on this 

```
batch = http.BatchHttpRequest(callback=batch_callback, batch_uri=_MessagingService.FCM_BATCH_URL)
```

on `messaging` file.

And the second log doesn't bother me much
https://stackoverflow.com/questions/52965123/dataflow-runner-attempting-refresh-to-obtain-initial-access-token#comment92852936_52965123

**Comment by hiranya911** [comment]
We don't log anything. What you're seeing is a runtime error. Most likely caused by an old or incompatible version of `google-api-client` in the Python path.

**Comment by b3g00d** [comment]
I found `google-api-client` required position argument
If you use named argument on 
`http.BatchHttpRequest` `google-api-client` will not produce log like
`__init__() takes at most 1 positional argument (3 given)`

**Comment by fenikso** [comment]
In the current version of google-api-python-client (1.7.11) it still requires keyword arguments.

**Comment by nicolabaldo81** [comment]
,
