### ISSUE TITLE
504 Deadline Exceeded trying to make a single write

### ISSUE THREAD

**Issue by amritsub** [firebase/firebase-admin-python#308]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OS X Mojave 10.14.3
  * Firebase SDK version: 2.17.0
  * Library version: _____
  * Firebase Product: Firestore

### [REQUIRED] Step 3: Describe the problem
Trying to a simple write results in a Deadline Exceeded Error:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    doc_ref.set(product_dict)
  File "/Users/.../env/lib/python2.7/site-packages/google/cloud/firestore_v1/document.py", line 234, in set
    write_results = batch.commit()
  File "/Users/.../env/lib/python2.7/site-packages/google/cloud/firestore_v1/batch.py", line 147, in commit
    metadata=self._client._rpc_metadata,
  File "/Users/.../env/lib/python2.7/site-packages/google/cloud/firestore_v1/gapic/firestore_client.py", line 1042, in commit
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/Users/.../env/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/.../env/lib/python2.7/site-packages/google/api_core/retry.py", line 273, in retry_wrapped_func
    on_error=on_error,
  File "/Users/.../env/lib/python2.7/site-packages/google/api_core/retry.py", line 182, in retry_target
    return target()
  File "/Users/.../env/lib/python2.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/.../env/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/Users/.../env/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
```

#### Steps to reproduce:
see code below:

#### Relevant Code:

```
from firebase_admin import firestore, credentials

cred = credentials.Certificate("<path to service account>")
firebase_admin.initialize_app(cred)
print("initialized firebase successfully")

product_dict={
  'test1': 'test',
  'test2': 'test2'
}
firestore_client = firestore.client()
doc_ref = firestore_client.collection('products').document('test')
doc_ref.set(product_dict)
```

**Comment by cmcjacob** [comment]
Same exact issue with latest package python 3.4 and Windows 10.

**Comment by eliasor96** [comment]
Same exact issue with firebase-admin 2.17.0 and python 3.7.3

**Comment by hiranya911** [comment]
Can you indicate the version of `google-cloud-firestore` installed in your environments?

**Comment by eliasor96** [comment]
1.3.0.
Upgrade to python 3.7.4 fixed the problem at my case

**Comment by hiranya911** [comment]
@eliasor96 does the problem reoccur if you go back to Python 3.6? If so can you please file an issue at https://github.com/googleapis/google-cloud-python/tree/master/firestore

**Comment by hiranya911** [comment]
@tseaver @crwilcox have you seen anything like this?

**Comment by amritsub** [comment]
seems to work for me now, i'm wondering if there was any recent incident with Firestore that may have caused this issue

**Comment by hiranya911** [comment]
I'm going to close this based on OP's last comment. If the problem resurfaces, please follow up by raising an issue at https://github.com/googleapis/google-cloud-python/tree/master/firestore
