### ISSUE TITLE
download url in firebase format

### ISSUE THREAD

**Issue by aminm2a** [firebase/firebase-admin-python#351]
Hi, 

I'm uploading a file using **upload_from_filename**. The file is uploaded correctly to firebase storage and I retrieve the file 's download link usingblob.media_link. This gives a valid url that opens in chrome but I'm enable to download the file using this url in firebase android SDK. 
The raised error is: **Firebase Storage URLs must point to an object in your Storage Bucket. Please obtain a URL using the Firebase Console or getDownloadUrl()**.
The url given by firebase-admin starts with https://storage.googleapis.com/.. 
whereas the correct url should start with https://firebasestorage.googleapis.com/v0/..

How can I get the correct url ?

**Comment by hiranya911** [comment]
It's not supported. Firebase download URLs are different from the signed URLs you get from the `google-cloud-storage` module that gets used in back-end environments. You should probably try to directly open the URL in the Android app without going through the Firebase Storage SDK.

I'm not sure if there are any plans to resolve this incompatibility. I just know it's a somewhat complex issue. I'll try to get somebody from the Storage team to have a look.

**Comment by hiranya911** [comment]
@schmidt-sebastian this is specifically for the Python APIs, but you might be able to give a more general answer from the Firebase Storage/GCS points of view.

**Comment by schmidt-sebastian** [comment]
What @hiranya911 is unfortunately correct. You can use "gs://..." URLs in the Firebase Storage SDKs or obtain Firebase Storage SDK-friendly public URLs via the Firebase Console. The most secure and recommended way is to access the object via the "gs://" URLs.

**Comment by duhaime** [comment]
@hiranya911 @schmidt-sebastian Would either of you be able to give more information on how one can convert a path with the "gs://" protocol to a "http" or "https" protocol path? I'd be grateful if you could.

**Comment by schmidt-sebastian** [comment]
If your data is private, please follow the steps here: https://stackoverflow.com/questions/42956250/get-download-url-from-file-uploaded-with-cloud-functions-for-firebase

If all your data is public, you can generate these URLs yourself. The URLs follow the format outlined here: https://cloud.google.com/storage/docs/access-public-data

**Comment by duhaime** [comment]
Many thanks @schmidt-sebastian--this is very helpful!

**Comment by duhaime** [comment]
@schmidt-sebastian Thanks again for your help. I have one quick follow-up question: is there a way to make data public while uploading the data? In S3, for example, one can use `s3 cp myfile.txt s3://my-bucket/ --acl public-read`, where the acl flag sets the file permissions (in this case making the file open for reads by anyone). 

Is there something similar one can interject into the code block below to make the uploaded data public? If not, is there some kind of switch one can use elsewhere that makes a dataset public? Any pointers you can offer on this question would be very helpful!

```
import glob, os, firebase_admin
from firebase_admin import storage

cred = firebase_admin.credentials.Certificate('service-account.json')
firebase_admin.initialize_app(cred, {
  'databaseURL': 'https://my-app-name.firebaseio.com/',
  'storageBucket': 'my-app-name.appspot.com/',
})

blob = storage.bucket('my-app-name.appspot.com').blob('a.jpg')
blob.upload_from_filename('cats.jpg') 
print(blob.public_url) 
```

**Comment by schmidt-sebastian** [comment]
You can make all data in a bucket publicly readable by default: https://cloud.google.com/storage/docs/access-control/making-data-public

**Comment by the-kool-sk** [comment]
https://stackoverflow.com/questions/53304517/how-to-retrieve-image-from-firebase-storage-using-python

this might help you @aminm2a
