### ISSUE TITLE
FR: Multi Tenancy Support like in Node SDK

### ISSUE THREAD

**Issue by Dinuz** [firebase/firebase-admin-python#353]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS Mojave 10.14.6
  * Firebase SDK version: 3.0
  * Library version: _____
  * Firebase Product: AUTH (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem

@hiranya911 
Would be terrific if we could support multi tenancy as it is in the Node sdk.
Is something like this in the pipeline?
I do think many users will love or benefit in having a multi-tenant support also for python.

**Comment by hiranya911** [comment]
Hi @Dinuz. We definitely want to support it in Python at some point. But it will probably be a while before we can get around to it (couple of other action items in the pipeline that have more priority right now). I'm putting a help-wanted label on this now. Hopefully somebody in the open source community can help us speed things up by providing pull requests.

**Comment by Dinuz** [comment]
Hello @hiranya911 I will look into it too, and try to help as much as I can.
Thank you for answering back. I tried the node sdk and it is a pretty sweet functionality (for now I can bypass it using node in a microservices, but clearly python would be much better - well at least I would prefer).

**Comment by sww314** [comment]
This is blocker for us in adopting Identity Platform. We need multi-tenant and all our existing backend code is in Python. Moving to node.js is non-starter.

**Comment by hiranya911** [comment]
This has been implemented in the `multitenancy` branch. Will be released son.
