### ISSUE TITLE
firebase_admin 

### ISSUE THREAD

**Issue by alexarsh** [firebase/firebase-admin-python#379]
* Operating System version: Ubuntu 18.04.3
  * Firebase SDK version: 2.7.0
  * Firebase Product: database

I have a Tornado app which is using python firebase_admin SDK.
When I run in single process:

    console_server = tornado.httpserver.HTTPServer(ConsoleApplication())
    console_server.listen(options.console_port, options.bind_addr)
    tornado.ioloop.IOLoop.instance().start()

firebase_admin works fine. But when I change it to run in multiprocess:

    console_server = tornado.httpserver.HTTPServer(ConsoleApplication())
    console_server.bind(options.console_port, options.bind_addr)
    console_server.start(4)
    tornado.ioloop.IOLoop.instance().start()

The last line here is getting stuck:

    if (not len(firebase_admin._apps)):
         cred = ...
         self.app = firebase_admin.initialize_app(cred)
    self.app = firebase_admin.get_app()
    self.db = firestore.client()
    ...
    ref = self.db.document(USER_DOC.format(org, value))
    user_ref = ref.get()

Seems like get() is not getting resolved since I don't get any exception.

Does anyone has an idea why it's happening?

**Comment by hiranya911** [comment]
I'd recommend asking the Tornado community for some help. I don't know what you mean by "not getting resolved". If there was an error in the SDK level, I'd expect to see some sort of an error message or exception stack trace. Perhaps there is an exception that your server environment is not exposing.
