### ISSUE TITLE
Comparison with `is`

### ISSUE THREAD

**Issue by BeneCollyridam** [firebase/firebase-admin-python#382]
### Code choice
In [`firebsae_admin/_token_gen.py` line 290-291](https://github.com/firebase/firebase-admin-python/blob/master/firebase_admin/_token_gen.py#L290)
I noticed the sub-expression: `payload.get('v') is 0` and I was wondering if this shouldn't be `payload.get('v') == 0`. 

I know that integers from -5 to 256 are cached in CPython, but I don't think it is good to rely on that when checking for equality (if that is the case).

**Comment by hiranya911** [comment]
Fixed in #384
