### ISSUE TITLE
thank you google for the firebase support on the xilinx-pynq board

### ISSUE THREAD

**Issue by vishwas1234567** [firebase/firebase-admin-python#399]
![image](https://user-images.githubusercontent.com/48592314/73462962-8eeed080-43a2-11ea-8d0b-ba01229e3555.png)

**Comment by vishwas1234567** [comment]
so good to see this running in the pynq board

**Comment by hiranya911** [comment]
I think you ought to thank the people at https://github.com/ozgur/python-firebase. We don;t develop `python-firebase`.
