### ISSUE TITLE
@hiranya911

### ISSUE THREAD

**Issue by rahulj3716** [firebase/firebase-admin-python#411]
@hiranya911 
I am using the string value as it is from service account key JSON without the help of environment still it is showing the same error.
Please help its super urgent.

_Originally posted by @rahulj3716 in https://github.com/firebase/firebase-admin-python/issues/188#issuecomment-585756045_

**Comment by hiranya911** [comment]
Please follow up through StackOverflow or contact Firebase support. This is not a support channel. And when you do follow up, please specify the code you're trying to run and any error messages you're seeing.
