### ISSUE TITLE
FR: SignIn user with email and password to get uid or token

### ISSUE THREAD

**Issue by ArpitKotecha** [firebase/firebase-admin-python#425]
There is no way to get the user uid after verifying both email and password.

Use Case:-

- If a user login from a new device there is no way to get the token after verifying both email and password.
- Or after user logs out and wants to login again since there will be no token the only way to get new token is only through email or phone number which is not secure since password is not verified.

**Comment by hiranya911** [comment]
I think you're in the wrong repo. There are no user login APIs in this library.

**Comment by ArpitKotecha** [comment]
Hi, I was looking if it can be built as it would make flow easier.

**Comment by ArpitKotecha** [comment]
Else how would a uid be fetched in backend which is needed to get jwt token.

**Comment by hiranya911** [comment]
We don't expose user auth APIs in Admin SDKs. That's not what these libraries are typically used for. You should implement user auth functionality on the client devices (mobile device or web browser), using one of the Firebase client SDKs.

**Comment by ArpitKotecha** [comment]
Ok Thanks
