### ISSUE TITLE
FR: Handle multiple Firestore projects

### ISSUE THREAD

**Issue by rjourdan** [firebase/firebase-admin-python#454]
I found a [similar case for Firebase](https://github.com/firebase/firebase-admin-python/issues/173) that has been resolved but could not find a way on Firestore to work simultaneously on multiple databases/projects.

```
import firebase_admin
from firebase_admin import credentials, auth
from firebase_admin import firestore

#Firestore client init for EMEA db
cred1 = credentials.Certificate('path/to/serviceAccountKey1.json')
firebase_admin.initialize_app(cred1)
db_emea = firestore.client()

#Firestore client init for US db
cred2 = credentials.Certificate('path/to/serviceAccountKey2.json')
firebase_admin.initialize_app(cred,options=None, name='US')
db_us = firestore.client()
```

I can't perform operations at the same time on both database. 
Any ideas?

**Comment by hiranya911** [comment]
`firestore.client()` takes an optional `app` argument. 

https://firebase.google.com/docs/reference/admin/python/firebase_admin.firestore

**Comment by rjourdan** [comment]
thank you for the pointer! For some reasons, I could not find that. 
For other people looking at the same, here is the code that works

```
import firebase_admin
from firebase_admin import credentials, auth
from firebase_admin import firestore

#Firestore client init for EMEA db
cred1 = credentials.Certificate('path/to/serviceAccountKey1.json')
app_emea = firebase_admin.initialize_app(cred1)
db_emea = firestore.client(app=app_emea)

#Firestore client init for US db
cred2 = credentials.Certificate('path/to/serviceAccountKey2.json')
app_us = firebase_admin.initialize_app(cred,options=None, name='US')
db_us = firestore.client(app=app_us)
```

**Comment by tycooperaow** [comment]
What about handling multiple firestore cloud storage?

**Comment by tedescolor** [comment]
What about handling multiple messaging? Really thanks

**Comment by dsin** [comment]
> What about handling multiple messaging? Really thanks

by passing app arguments in messaging.send()

myapp = firebase_admin.initialize_app(cred, name='my-firebase-app')
... 
response = messaging.send(message, app=myapp)

improved response from [here](https://stackoverflow.com/questions/74631191/how-to-sent-push-message-from-multiple-apps-in-python)
