### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by Monsieurvishal** [firebase/firebase-admin-python#463]
I installed it using 
pip install python-firebase using anaconda command promt
installation was successful.
 I tried running in jupyter notebook
from firebase import firebase

and got following error
Traceback (most recent call last):

  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-6-13b1d3dca18c>", line 1, in <module>
    from firebase import firebase

  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\firebase\__init__.py", line 3
    from .async import process_pool
              ^
SyntaxError: invalid syntax

![Screenshot (107)](https://user-images.githubusercontent.com/59202862/82314752-e2376e00-99e7-11ea-9e80-472294672dfc.png)

**Comment by Monsieurvishal** [comment]
async is a keyword in Python 3.7, it looks like firebase is not compatible with Py3.7
Following steps helped  me:
rename .async into .async_
open__init__ file and change .async into .async_
open firebase.py and change .async into .async_

Youtube vedio:  https://www.youtube.com/watch?v=QmskD6utEuI
Its clear now

**Comment by hiranya911** [comment]
Also this repo has nothing to do with `python-firebase` package. This repo is for `firebase-admin`.
