### ISSUE TITLE
The same function work in local machine but fail in Google cloud function

### ISSUE THREAD

**Issue by yashhema** [firebase/firebase-admin-python#468]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Google Cloud Functions
  * Firebase SDK version: What is provided there (just said - firebase-admin )in requirements.txt
  * Library version: As provided in google cloud
  * Firebase Product: _____ database

### [REQUIRED] Step 3: Describe the problem
The below code works in my laptop - but fails in google cloud
        transaction = db.transaction()
        entity_ref = db.collection(entitytype).document()		
        transaction.set(entity_ref,entitydata)		
       
        
        createdbyappuser=entitydata["createdby"]
        Function1(db,transaction)
        print("out of entity creation")
        transaction.commit()

        transaction1 = db.transaction()
        
        print("adding staff")
        Function2(db,transaction1)
        print("out of staff")

        transaction1.commit()

with in function2 - we get the error when it tries to transaction.get 
the error is - ValueError: Transaction not in progress, cannot be used in API requests.
Internally function2 calls some other function, cloudfunction gives a error  - 

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
Just create a new transaction, after commiting an old transaction

**Comment by hiranya911** [comment]
Possibly a missing decorator or a similar programming error: https://stackoverflow.com/questions/61493125/transaction-not-in-progress-cannot-be-used-in-api-requests-firestore-error

If you continue to experience problems, please reach out to Firebase Support directly and provide a minimal, complete code sample to reproduce the problem.
