### ISSUE TITLE
`create_custom_token` uses deprecated `SignJwt` API

### ISSUE THREAD

**Issue by olance** [firebase/firebase-admin-python#471]
### Describe your environment

  * Operating System version: macOS 10.15
  * Library version: v4.3.0
  * Firebase Product: auth

### Describe the problem

Google Cloud Platform sent out an email yesterday:

> **[Action Required] Calls to IAM SignBlob and SignJwt won’t be supported as of July 1, 2021**
>
> IAM SignBlob and SignJwt on the IAM API will be decommissioned. Move your projects to the new IAMCredentials API.

One of my projects was listed as affected, and I could trace the API call down to my use of `create_custom_token` from this `firebase-admin` package.
This method ultimately calls some signing method from `google-auth-library-python`, which makes the actual API call.

An issue has been open on the `google-auth-library-python` repository already: https://github.com/googleapis/google-auth-library-python/issues/543, and I thought one should be created here so that it can be tracked, and this package's dependencies be updated as soon as the auth lib is fixed.

#### Relevant Code:

```python
from firebase_admin import auth as firebase_auth
token = firebase_auth.create_custom_token(user_id, claims)
```

**Comment by hiranya911** [comment]
This should be fixed now. Installing firebase-admin now pulls the latest versions of google-auth which contain the necessary fix.
