### ISSUE TITLE
Requested entity was not found - Multicast message

### ISSUE THREAD

**Issue by charlesabetzntt** [firebase/firebase-admin-python#481]
Hi 

I am having difficulty understanding why one device token will fail, but if I use that token in the Cloud Messaging Console (https://console.firebase.google.com/) it works as expected, ie: sends the notification to the device.

The Registration tokens are stored in a db and are retrieved and placed into array list. 

Below code works for most devices, but seems to fail for iPhone 10 with "Requested entity was not found".

`message = messaging.MulticastMessage(notification=messaging.Notification(title="Title"), body="Body"),data={"data": data},tokens=registration_tokens) `  
    `response = messaging.send_multicast(message)`
    `# See the BatchResponse reference documentation`
    `# for the contents of response.`
    `print('{0} messages were sent successfully'.format(response.success_count))`
    `print('{0} messages that failed to be sent'.format(response.failure_count))`
    `for r in response.responses:`
      `  if not r.success:`
            `print('{0} responses'.format(r.exception))`

Is there anything more detail that I can find out to see why it is failing, also what does the above error mean?

**Comment by chong-shao** [comment]
Hi @charlesabetzntt , it will be helpful to know the registration token, project id, and full sample request / response for investigation on this type of issues. I'd suggest starting from https://firebase.google.com/support and filing a support ticket. Thanks!
