### ISSUE TITLE
create_ios_app OAuth limitation too strict

### ISSUE THREAD

**Issue by ChristopherDrum** [firebase/firebase-admin-python#483]
* Operating System version: macOS 10.15.5
* Firebase SDK version: v3.0.1
* Library version: v4.3.0
* Firebase Product: admin

### [REQUIRED] Step 3: Describe the problem
I use a python script on Xcode Server to register new bundle identifiers with Firebase App Distribution.
This is similar (though modified) from what I used to do when Fabric was the distribution method for our various internal prototypes.

Now, I'm suddenly getting `UnknownError` when doing trying to register new bundle IDs.
Specifically, when I run `create_ios_app` and try to use the return value on `get_config()` I am told 
`AttributeError: 'NoneType' object has no attribute 'get_config'`

#### Relevant Code:

With no changes to my script nor to the server running the script, this line of code that has been working flawlessly for a long time (a year?) is suddenly returning a `NoneType`.
```
target_app = firebase_admin.project_management.create_ios_app(bundle_id=newBundleId, display_name=newDisplayName, app=firebase_app)
```

Manually running the relevant code in Python3 interactive mode returned the following
```
>>> target_app = firebase_admin.project_management.create_ios_app(bundle_id=newBundleId, display_name=newDisplayName, app=firebase_app)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/project_management.py", line 115, in create_ios_app
    return _get_project_management_service(app).create_ios_app(bundle_id, display_name)
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/project_management.py", line 577, in create_ios_app
    return self._create_app(
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/project_management.py", line 599, in _create_app
    poll_response = self._poll_app_creation(operation_name)
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/project_management.py", line 617, in _poll_app_creation
    raise exceptions.UnknownError(
firebase_admin.exceptions.UnknownError: Polling finished, but the operation terminated in an error.
```

**Comment by hiranya911** [comment]
Does not repro to me. Can you try catching the above exception and then logging its `http_response` property?

```
try:
  create_ios_app(...)
except Exception as ex:
  print('Status:', ex.http_response.status_code)
  print('Content:', ex.http_response.content.decode())
```

**Comment by ChristopherDrum** [comment]
@hiranya911 Well, thank you for that troubleshooting info.
It turned up some useful information, rather than the original generic "UnknownError"

```
Status: 200 Content: { "name": "operations/projects/<REDACTED>/apps/<REDACTED>", "done": true, "error": { "code": 8, "message": "Number of OAuth clients created exceeded limit.", "details": [ { "@type": "type.googleapis.com/util.StatusProto", "code": 38, "space": "firebase-error", "message": "Number of OAuth clients created exceeded limit.", "canonicalCode": 8 } ] }
```

**Comment by ChristopherDrum** [comment]
OK, found the documentation here
https://firebase.google.com/support/faq

```
A project is a container for apps across iOS, Android and web. While there is no restriction on number of apps within a project, adding an app can create one or more underlying OAuth 2.0 client IDs. There is a limit of around 30 client IDs that can be created within a single project.
```

**Comment by ChristopherDrum** [comment]
So this isn't really a python SDK issue, but really just a Firebase general issue. I'll elevate to the proper team.

**Comment by hiranya911** [comment]
Thanks for reporting your findings @ChristopherDrum. We will also try to improve the SDK implementation so the error details are more visible to the developers.
