### ISSUE TITLE
Bug: it takes a lot of time to do any operation with firebase admin sdk in python (around 15 mins)

### ISSUE THREAD

**Issue by sudonims** [firebase/firebase-admin-python#488]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: __debian bullseye kernel 5.7.0___
  * Firebase SDK version: _____
  * Library version: _____
  * Firebase Product: ___all__ (auth, database, storage, etc)

#### Steps to reproduce:

What happened? How can we make the problem occur?
you can try firebase admin sdk for doing any operation and it will show the problem

#### Relevant Code:
decoded_token = auth.verify_id_token(token)
user_id = decoded_token['uid']
docs = db.collection(u'users').document(user_id).collection('experiments')

127.0.0.1 - - [10/Sep/2020 00:34:51] "OPTIONS /getworkspace/123_retrain HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2020 00:34:51] "OPTIONS /getworkspace/all HTTP/1.1" 200 -
trying  //before_request
trying  //before_request
127.0.0.1 - - [10/Sep/2020 00:45:53] "GET /getworkspace/123_retrain HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2020 00:45:53] "GET /getworkspace/all HTTP/1.1" 200 -
```
// TODO(you): code here to reproduce the problem
```

**Comment by hiranya911** [comment]
Can you clarify your issue with a clear example please? The code shown above only takes a few milliseconds to run.

**Comment by sudonims** [comment]
If you see I've also put the flask output there about the requests it are making...when it prints 'trying' it is before the request, trying to decode the auth token...but the process is taking about 10 mins...and once token is verified it goes to GET request part where db operation takes 1- 1.5 mins...You can see the timestamp there ....

**Comment by hiranya911** [comment]
Without a minimal and complete repro it's impossible to make out anything. The APIs you describe are widely used, and are often tested by our CI. I think a network glitch or some other environment-specific issue better explains what you observed.
