### ISSUE TITLE
count of users does not match

### ISSUE THREAD

**Issue by chaitanya4288** [firebase/firebase-admin-python#496]
Operating System version: MacOS Catalina 10.15.6
Firebase SDK version: 7.14.3
Library version: 4.3.0
Firebase Product: auth

The user count shown in the console and the count obtained by iterating all the users via admin sdk don't seem to match.

In the console, under the authentication section, the count can be seen in the pagination information.

![image](https://user-images.githubusercontent.com/2232566/96585203-e0f2d000-12fc-11eb-94c4-361157544691.png)

In the above pic, the count seems to be: 936701

Where as when the count is obtained via admin sdk gives: 906553

I am using list_users to iterate over the users. Here is the following code

```
    count = 0
    page = auth.list_users()
    while page:
        for user in page.users:
            count = count + 1
        page = page.get_next_page()

    print("The count of users is: {0}".format(str(count)))

```

The counts seem to be different. Which one is the correct count?

**Comment by chaitanya4288** [comment]
Hello team, any update on this issue?

**Comment by hiranya911** [comment]
Doesn't repro on our test projects. But they also don't have as many users (only around 400 users). 

@bojeil-google is it possible the UI displays duplicates in certain cases?

**Comment by bojeil-google** [comment]
This is a known issue in the total counter. I think there are cases where the counter goes off due to duplication. If the counter is off in the UI, please file a bug with [support](https://firebase.google.com/support) to reset it.
