### ISSUE TITLE
FR: Support for authentication emulator

### ISSUE THREAD

**Issue by karloskar** [firebase/firebase-admin-python#503]
* Operating System version: Ubuntu 20.04
  * Firebase SDK version: 8.1.1
  * Library version: 4.4.0
  * Firebase Product: auth

It would be excellent if the Firebase Admin Python SDK could connect to the local authentication emulator. Similar issues exists for [the Go version](https://github.com/firebase/firebase-admin-go/issues/409) and for the [Java version](https://github.com/firebase/firebase-admin-java/issues/493).

**Comment by stefanadelbert** [comment]
I second this feature request.

**Comment by yuchenshi** [comment]
b/173548888 for internal tracking purposes.

**Comment by Keramblock** [comment]
So, any news about it?

**Comment by Keramblock** [comment]
@hiranya911 ?

**Comment by hiranya911** [comment]
Nothing new to share. Although we do accept pull requests. Somebody just implemented this feature for our [Go SDK](https://github.com/firebase/firebase-admin-go/pull/414). If somebody can port that change into this repo, we can take a look and get it ready for an upcoming release.

**Comment by Keramblock** [comment]
@muru thanks for the fix! 
@hiranya911 could you please take a look? =)

**Comment by bobatsar** [comment]
Hi there, isn't this already published via PyPi? Seems to be included since 5.0.0.
Shouldn't then the table in https://firebase.google.com/docs/emulator-suite/install_and_configure#admin_sdk_availability be updated to reflect that it is working with python?

**Comment by lahirumaramba** [comment]
@bobatsar You are correct! We just updated the table in https://firebase.google.com/docs/emulator-suite/install_and_configure#admin_sdk_availability. Thank you bringing this to our attention.
