### ISSUE TITLE
FR: Use Firestore client credentials with firestore emulator 

### ISSUE THREAD

**Issue by paulharter** [firebase/firebase-admin-python#513]
It would be nice to be able to run tests against a local Firestore emulator that respected the credentials in the client, at the moment they are discarded when connecting to the emulator. This would allow tests of firestore rules in python.

This can be done by replacing `grpc.ssh_channel_credentials()` with `grpc.local_channel_credentials()` in the grpc channel when `_emulator_host` is used.

Would you accept a pull request doing this

thanks

P

**Comment by hiranya911** [comment]
Thanks for the feature request @paulharter. Couple of points:

1. Firestore Python SDK is developed at https://github.com/googleapis/python-firestore. So any pull requests should be submitted there.
2. Server-side Firestore interactions are not subjected to rules checks (regardless of the credentials being used). This is a known limitation with Firestore at the moment: https://firebase.google.com/docs/firestore/security/overview

**Comment by paulharter** [comment]
@hiranya911 

1 - Sorry for being in the wrong place. I'll go over there.

2 - The python admin SDK can be used to interact with firestore as if it was a client and it does use the rule checks if you use credentials wrapped round a custom token. This has worked for a while now

Thanks
