### ISSUE TITLE
FR: Split dev dependencies into separate file

### ISSUE THREAD

**Issue by allentv** [firebase/firebase-admin-python#523]
I see a difference in the list of dependencies in `requirements.txt` and `setup.py` which I would assume because they are updated separately. Would it be easier to have the list of dependencies in just `requirement.txt` and read them directly from `setup.py`? The non-essential ones (related to development) can be added to a separate file called `dev.requirements.txt`

**Comment by hiranya911** [comment]
`setup.py` is used by Python package managers. 

`'requirement.txt` is meant to be used by developers and CI workflows that have access to the full source code checked out from the repo.

Beyond that we don't intend to make any distinction.
