### ISSUE TITLE
Firebase with nameko

### ISSUE THREAD

**Issue by Riglanto** [firebase/firebase-admin-python#529]
Calling firebase admin from nameko rpc results in blocked api calls to:

```
Making request: POST https://oauth2.googleapis.com/token
Starting new HTTPS connection (1): oauth2.googleapis.com:443 # After that nothing happens
```

I've even created as SO post about that - you can see more details here: https://stackoverflow.com/questions/65959369/firestore-https-calls-blocked-inside-the-nameko-rpc-function

Difficult to say if that's an issue or async calls are still not supported as discussed here: https://github.com/firebase/firebase-admin-python/issues/104

As REST is no longer supported - `Database secrets are currently deprecated` - the only workaround is to call it via separated python script and `subprocess.run()` method.

Looking forward to any comments or clarification.

**Comment by hiranya911** [comment]
Not familiar with nameko. You should probably try running the [`google-cloud-firestore`](https://pypi.org/project/google-cloud-firestore/) package directly within your framework to see if that's supported.

**Comment by hiranya911** [comment]
I'm going to close this. If the problem continues to exist, I'd suggest reaching out to the Firestore Python project or the Nameko community.
