### ISSUE TITLE
ETA for storage or transaction support?

### ISSUE THREAD

**Issue by alexanderwhatley** [firebase/firebase-admin-python#53]
Hi, I was wondering if/when this API will support writing files to storage, and transaction support. Either of these things would be very useful for the work I am doing. Thanks.

**Comment by rockwotj** [comment]
The Realtime Database just added support for conditional requests (AKA transactions) via the REST API.

The docs for this are here: https://firebase.google.com/docs/reference/rest/database/#section-conditional-requests

We're open to Pull Requests 😄 

/cc @caseycrogers

**Comment by rockwotj** [comment]
Also to track Google Cloud Storage for Firebase integration, you'll want to watch this PR: https://github.com/firebase/firebase-admin-python/pull/44
