### ISSUE TITLE
New document ID not unique after fork

### ISSUE THREAD

**Issue by jdsutton7** [firebase/firebase-admin-python#548]
If firebase_admin is imported before os.fork(), auto-generated document IDs are repeated causing data to be overwritten. 

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux Mint 20
  * Firebase SDK version: 5.0.0
  * Library version: _____
  * Firebase Product: firestore

#### Steps to reproduce:

Import firebase_admin, fork, create firestore client, write a new document.

#### Relevant Code:

```
#!/usr/bin/env python3.6

import os
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

pid = os.fork()

cred = credentials.Certificate('service_account.json')
firebase_admin.initialize_app(cred)

client = firestore.client()

if pid == 0:
    reference = client.collection('Test').document()
    reference.set({'a': 'b'})

    print('Child: ' + reference.id)
else:
    reference = client.collection('Test').document()
    reference.set({'a': 'c'})

    print('Parent: ' + reference.id)

```

**Comment by hiranya911** [comment]
Here's the output I'm getting on 3 separate runs:

```
Parent: EYva0t27NXfzSqlCzPgX
Child: bMEiYiVy4lVxs9k38oQe

Parent: o0iIaRfbvtswbCg9Jrt5
Child: 6bT2NOr4MjyF0irz8DcP

Parent: ijd9nx6IoHFVgAZDs6Ls
Child: iizfc35OSQFap7j4XbOx
```

**Comment by hiranya911** [comment]
If you can consistently reproduce the issue I'd advise directly reporting on the Firestore Python project at: https://github.com/googleapis/python-firestore

They should be able to help you out.
