### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by imesimone** [firebase/firebase-admin-python#551]
Hi,
I've just installed with pip3 this package (firebase_admin) on a Raspberry Pi Zero W (with the latest Rasbian w/o desktop environment). Everything is updated (even _apt update / upgrade_ has been tried). No missing dependency.

When I try to import firestore from firebase_admin, Python 3.7 crashes and reports "Illegal instruction".
Nothing more and, obviously, it is not possible to understand what is the problem in depth since it is not caught by any try...except.

```
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore  # Illegal instruction
```

Have you ever experienced the same issue? Any ideas?

**Comment by hiranya911** [comment]
My guess is the version of Firestore or gRPC installed is incompatible with your system. You should be able to repro this by directly importing Firestore as follows:

```
from google.cloud import firestore
```

Can you check if that's the case? If so you might have to report a bug at https://github.com/googleapis/python-firestore to get the proper assistance resolving it.
