### ISSUE TITLE
Make available objects.inv for intersphinx

### ISSUE THREAD

**Issue by cblegare** [firebase/firebase-admin-python#553]
Hello there!

We'd love to be able to cross reference our documentation with firebase_admin's, just like we can with other Google Cloud SDK library using intersphinx!

You simply need to make avaible a objects.inv file somewhere in the API reference web site, juste like https://googleapis.dev/python/logging/latest/index.html (see https://googleapis.dev/python/logging/latest/objects.inv)

**Comment by hiranya911** [comment]
@kevinthecheung do you know if this is feasible.

**Comment by cblegare** [comment]
I've looked around the firebase github org and didn't find any documentation repo.  I guess this is built internaly somewhere with this repo as a submodule.  I can tell Sphinx is used to render the HTML with a quick source inspection, so the objects.inv must be built at some point.  Since the API reference is rendered for multiple language, maybe the URLs sphinx knows about would not be the right one.

For managing the inventory file, the magic happens in the [`sphinx.util.inventory` module](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/util/inventory.py)

In case you need post-processing the inventory file, you might be interested in https://github.com/bskinn/sphobjinv

So I guess the hard work would not happen in this repo exactly, or anywhere I could find in a public repository.  Still, that would be really nice :)

I hope this helps!

**Comment by kevinthecheung** [comment]
Hi Charles,

We started publishing the `objects.inv` file today: https://firebase.google.com/docs/reference/admin/python/objects.inv

Sorry this took so long! I don't get issues assigned to me often, so I wasn't looking out.

Please re-open if this isn't working.

**Comment by cblegare** [comment]
Thank you @kevinthecheung !
