### ISSUE TITLE
Custom token has invalid signature

### ISSUE THREAD

**Issue by Jihadik** [firebase/firebase-admin-python#556]
### Environment
  * Operating System version: OSX 10.15.7
  * Library version: 5.0.0 (also tried in 4.5.3)
  * Firebase Product: auth

### Problem
Custom tokens that are created via `firebase_admin` have invalid signature.

### Reproduction
1. Go to your Firebase account "Project Settings" -> "Service Account" and click "Generate new private key". Download it and put it locally
2. Execute in console
   ```sh
   export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json
   ```
3. Execute the following code snippet and copy the printed token
   ```py
   import firebase_admin
   from firebase_admin import auth
   firebase_admin.initialize_app()
   token = auth.create_custom_token("user-id")
   print(token)
   ```
4. Go to [jwt.io](https://jwt.io/), paste the token and get "Invalid Signature" verdict

**Comment by hiranya911** [comment]
That's not a useful way to validate these tokens. You need to pass them to the Firebase Auth service, or actually use them in a Firebase client SDK to perform a login. jwt.io do not have the keys required validate our custom tokens.

**Comment by hiranya911** [comment]
You will probably have to check with the FlutterFire team. We know for sure that the custom tokens generated by this library is accepted by the Firebase Auth backend. Here's our integration test for this use case:

https://github.com/firebase/firebase-admin-python/blob/527a8245e1ba461817be3f38ac142a0563daeb4d/integration/test_auth.py#L119-L123

**Comment by lahirumaramba** [comment]
@Jihadik how do you send the token from the Flutter side? The token might be truncated.. make sure you are sending the full token.
Also, despite getting the "Invalid Signature" on [jwt.io](https://jwt.io) you should still be able to decode the token and view its properties. The project id in the `iss` field of the token should match the project id of your client app is using. It should look something similar to `"iss": "firebaseserviceaccount@YOUR_PROJECT_ID.iam.gserviceaccount.com"`

**Comment by Jihadik** [comment]
@lahirumaramba, thanks for your suggestion, but I checked that before posting here :)
1. I was printing tokens on the server side as well as the client side and they are identical
2. I'm able to decode tokens on [jwt.io](https://jwt.io) and all the parameters are set correctly

**Comment by Jihadik** [comment]
It turned out the server was corrupting tokens. `create_custom_token` returns a binary string, which then when passed to DRF `serializers.CharField` converted it to `"b'token'"` string.
