### ISSUE TITLE
Can't Retrieve Data From Firestore On Linux Network

### ISSUE THREAD

**Issue by SonicRoshan** [firebase/firebase-admin-python#560]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Arch Linux 
  * Firebase SDK version: NONE
  * Library version: 5.0.1
  * Firebase Product: firestore (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem

I am using ```firebase_admin``` on python to retrieve data from firestore. The code freezes at ```doc_ref.get()``` and ```E0707 17:10:27.720866621    5988 ev_epollex_linux.cc:516]    Error shutting down fd 9. errno: 9``` is printed every two minuted. Interestingly, when I do a USB WiFi tethering from my android phone, the issue no longer persists.

#### Steps to reproduce:

Use the following code for a firebase project and make sure to put service keys.

#### Relevant Code:

```python
from firebase_admin import credentials, initialize_app, firestore

# Initializing Flask app.
# Initializing firebase admin SDK.
cred = credentials.Certificate("configs/firebase.json")
initialize_app(cred)

db = firestore.client()
print(db.collection(u'org_main_data').document(u'tefst').get().to_dict())
```

**Comment by hiranya911** [comment]
Please report at https://github.com/googleapis/python-firestore

**Comment by SonicRoshan** [comment]
Ok, thanks for the help
