### ISSUE TITLE
Firebase RTDB Listener doesn't work with FastAPI

### ISSUE THREAD

**Issue by DotSyndicate** [firebase/firebase-admin-python#561]
I have posted the same issue on the FastAPI repository as well. So, please bear with me.

Here is my code for a Firebase RTDB data collection:
firebase_config.py:
```Python
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db


class FirebaseConfig:
    reference = None
    listenerRegistration = None

    def __init__(self):
        cred = credentials.Certificate("path_to_credentials.json")
        firebase_admin.initialize_app(
            cred,
            {'databaseURL': 'database_url'}
        )
        self.reference = db.reference("Users")
        self.listenerRegistration = self.reference.listen(self.userListener)

    def userListener(self, event):
        print("Listener Started.")
        try:
            print(event.data)
            updateData() # A function to update our local database
        except Exception as e:
            raise Exception("Listener Error" + str(e))

    def stopListening(self):
        print("Closing Listener")
        self.listenerRegistration.close()
```

main.py:
```Python
from fastapi import FastAPI
from firebase_config import FirebaseConfig


app = FastAPI()

@app.on_event("startup")
async def startup_event():
    global firConfig
    firConfig = FirebaseConfig()


@app.on_event("shutdown")
async def shutdown_event():
    firConfig.stopListening()
```
This problem may or may not be related to FastAPI as such. But here's the thing:
I have a project that uses Firebase RTDB, I want to maintain a copy of the same locally on my server. This server will be used to process the data and send it to the requesting clients. However, the data maybe updated regularly on Firebase RTDB which I am unable to update on my local database because it doesn't work with FastAPI for some reason.
The problem I am facing right now is that this listener doesn't work. The print statements don't print anything. I think this is because of FastAPI. Is there any way that I can make it work?

If they cannot work well together, do you have any alternative solutions for the same? I am not looking for an alternative to FastAPI as such but an alternative to the listener.

The above code is the most minimal code anyone will need to write to test the code. The only thing one will need to do is change some data on the Users node of the Firebase RTDB. I haven't included any code for get or post requests because they have nothing to do with my problem.

Why do I think it doesn't work with FastAPI?
I think this because if I comment the code inside `shutdown_event` function, then the listener prints the results of event.data after the server has shut down. 

### Environment

* OS: Linux: 18.1
* FastAPI Version [e.g. 0.3.0]:

To know the FastAPI version use: 0.65.2

* Python version: 3.7.4

**Comment by hiranya911** [comment]
Works for me:

```
% uvicorn main:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [52047] using watchgod
INFO:     Started server process [52049]
INFO:     Waiting for application startup.
Listener Started.
{'alice': 1}
INFO:     Application startup complete.
Listener Started.
{'bob': 2}
Listener Started.
3
```

Notice how the "Listener Started." has been logged 3 times along with the corresponding event data.

**Comment by DotSyndicate** [comment]
@hiranya911, do you mind sharing your code? Because I don't know why the same isn't working for me....

**Comment by DotSyndicate** [comment]
@hiranya911, I don't think it would have worked with just my code. So, that is why I am asking this. If you can please share your code, then I will be able to close the issue.

**Comment by hiranya911** [comment]
It's the exact same code, just put in the same file for simplicity:

```py
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db

from fastapi import FastAPI


class FirebaseConfig:
    reference = None
    listenerRegistration = None

    def __init__(self):
        cred = credentials.Certificate("../public/cert.json")
        firebase_admin.initialize_app(
            cred,
            {'databaseURL': 'https://admin-java-integration.firebaseio.com'}
        )
        self.reference = db.reference("Users")
        self.listenerRegistration = self.reference.listen(self.userListener)

    def userListener(self, event):
        print("Listener Started.")
        try:
            print(event.data)
        except Exception as e:
            raise Exception("Listener Error" + str(e))

    def stopListening(self):
        print("Closing Listener")
        self.listenerRegistration.close()


app = FastAPI()


@app.on_event("startup")
async def startup_event():
    global firConfig
    firConfig = FirebaseConfig()


@app.on_event("shutdown")
async def shutdown_event():
    firConfig.stopListening()
```

**Comment by DotSyndicate** [comment]
Hi. 
I think the error might be because of the port. I was using port 80 for my uvicorn server. I changed it and it worked. I don't know for sure. Thanks for the support.
