### ISSUE TITLE
Access token cannot be revoked in google account settings

### ISSUE THREAD

**Issue by VictorBebnev** [firebase/firebase-admin-python#564]
* Operating System version: Ubuntu 20.04
  * Firebase SDK version: 4.5.3
  * Firebase Product: auth
  * Python version: 3.7.10
  * Pip version: 21.1.1

#### Steps to reproduce:
1. Create a project with [google 0Auth](https://support.google.com/cloud/answer/6158849?hl=en)
2. Login with Google 0Auth 
3. Make sure the access or refresh token is valid.
4. Go to user GA settings: Manage your Google Account -> Security -> Third-party apps with account access
5. Remove your project from Third-party apps 
6. Check access and refresh tokens from step №2

Observed behavior: 
All tokens are valid

Expected behavior:
Access and refresh token revoked

**Comment by hiranya911** [comment]
This project has no bearing over Google OAuth2. Please file an issue against Google Cloud support.

**Comment by VictorBebnev** [comment]
This is not possible to push an issue for this component from [this page](https://cloud.google.com/identity-platform/docs/support).
Because [the link](https://issuetracker.google.com/issues/new?component=458130&template=1136497) is dead.
In the end, there is only one way - to pay for tech support. Haha, I discovered a security issue with your service, and I need to pay to pass it on to you? I just ignore it.

**Comment by hiranya911** [comment]
"Our service" is Firebase, which is independent from Google OAuth and Google Analytics. If you think you have found a bug in Firebase, you can file a case here (it's free for all Firebase users): https://firebase.google.com/support/troubleshooter/report
