### ISSUE TITLE
[FR] allow google-api-core[grpc] 2.X.X

### ISSUE THREAD

**Issue by jimcasteleiro** [firebase/firebase-admin-python#575]
I'm using `firebase_admin` in a project which has other services that interact with Google APIs. I would like to upgrade `google-api-core` to version 2, however, we are blocked by the requirement that `firebase_admin` use `google-api-core[grpc] >= 1.22.1, < 2.0.0dev`. and would like to change that to `< 3.0.0dev`.

Locally, I've run the test suite against `google-api-core[grpc]==2.0.1` and all of the tests passed. Does this collide with other planned work? I can open a PR on this.

**Comment by hiranya911** [comment]
Should be ok. I see that Firestore has already updated their requirement: https://github.com/googleapis/python-firestore/blob/51c92aa45156c5462f35991f65c02dcac49aacc3/setup.py#L31

**Comment by hiranya911** [comment]
Thanks for the PR. Change has been merged, and will be included in the next release.
