### ISSUE TITLE
FR: Provide a way to get all users or groups of users

### ISSUE THREAD

**Issue by grennis** [firebase/firebase-admin-python#60]
Would be great if the auth API provided:
- Possibility to a list of all users (or just the uids, if that is too expensive)
- Possiblity to get a list users given a list of uids (or possibly list of emails, phone numbers, etc. or even a mix/match of those)

**Comment by hiranya911** [comment]
I believe @bojeil-google has been working on something along the 1st requirement. 2nd requirement is supported in the backend REST API. I wonder if we should simply expose that in the SDK.

**Comment by bojeil-google** [comment]
1. list all users is in the works.
2. getting a list of users given a list of uids would be done with a wrapper for getUser. You can easily implement that. This is not a popular request unlike the first one.

**Comment by hiranya911** [comment]
@bojeil-google Since ID toolkit REST API accepts lists of UIDs, emails and phone numbers, can we implement a bulk get with just one call to the server (as opposed to getting one user at a time, in a loop)? I agree, it's not a very common feature request. I'm just curious to know.

**Comment by bojeil-google** [comment]
This is really a low priority. It is actually the first time i see this request. There are many other critical features that have higher priority. I personally don't think we should support it until we see a decent amount of requests for it.

**Comment by windsurfdrew** [comment]
We're creating firebase users that only exist for the duration of the session, along the lines of the [firebase for real time events example](https://cloud.google.com/solutions/using-firebase-real-time-events-app-engine). We need to periodically clean up the orphaned firebase users from clients who have not exited gracefully. It would be helpful both to get the full list of users and be able to bulk delete a set of users.

**Comment by hiranya911** [comment]
@windsurfdrew We released this [API](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#listUsers) for Node.js today. It will be ported to Python soon. If you like you can also help us expedite the launch by providing a pull request.

The Node.js implementation can be found at https://github.com/firebase/firebase-admin-node/blob/master/src/auth/auth.ts#L200

**Comment by hiranya911** [comment]
This was released in v2.6.0
