### ISSUE TITLE
[Auth] verify_id_token raises RecursionError 

### ISSUE THREAD

**Issue by GabrielBlondeau-Kirby** [firebase/firebase-admin-python#601]
**Thank you for submitting your issue. We are operating at reduced capacity from Dec 17 2021 to Jan 4 2022. Please expect delayed responses. For more urgent requests please reach us via our support channels https://firebase.google.com/support**

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux - Ubuntu 20.04
  * Firebase SDK version: 5.2.0
  * Firebase Product: auth
  * Python version: 3.8.12
  * Pip version: 21.1.1
  * oauth2client: 4.1.3

#### Steps to reproduce:

What happened? How can we make the problem occur?
it occurs only when my server is running, in a python console it works.

When I call the `verify_id_token` method like this: `auth.verify_id_token(<bearer_token>)` then I get the following error:
> `maximum recursion depth exceeded while calling a Python object`

The far point I manage to reach is: 
```
                verified_claims = google.oauth2.id_token.verify_token(
                    token,
                    request=request,
                    audience=self.project_id,
                    certs_url=self.cert_url)
```
From `_JWTVerifier.veridy` from the file `_token_gen.py`.

#### Relevant Code:
My server example
```
# coding=utf-8
import os
import json
import bottle
import firebase_admin

from firebase_admin import credentials
from bottle import Bottle, request, response

app = Bottle(catchall=False)
# Firebase doc: https://firebase.google.com/docs/admin/setup/#initialize-sdk
cred = credentials.Certificate(json.loads(os.environ.get('FIREBASE_CREDENTIALS')))
firebase_app = firebase_admin.initialize_app(credential=cred)

import settings  # All the settings the server needs
from routes import setup_routing  # All routes for my API

setup_routing(app)
```

How I'm checking and extract info from a JWT token
```
def extract_auth_from_token(bearer_token):
    decoded_token = auth.verify_id_token(bearer_token)
    jwt_id = decoded_token['user_id']  # user_id is the JWT user ID
    email = decoded_token['email'] if decoded_token.get('provider_id') != 'anonymous' else 'anonymous'
    context = {
        'jwt_id': jwt_id,
        'email': email
    }
    return context
```

------

~The weird thing is I'm getting proper Firebase Errors like `ExpiredIdTokenError` or `InvalidIdTokenError` if something is wrong with the jwt.~

------

Thank for reading it.
Gabriel

**Comment by lahirumaramba** [comment]
We have [nightly](https://github.com/firebase/firebase-admin-python/runs/4739795779?check_suite_focus=true) integration [tests](https://github.com/firebase/firebase-admin-python/blob/684bd248b5aa6d4ae07eae7c1cd6b0e098a1e325/integration/test_auth.py#L119) set up on the `verify_id_token` API and I don't see any test failures there. Would you be able to provide us with a minimal but complete repro for this? A complete script that we can run to reproduce the issue or a simple github project would work (omit any sensitive information, keys etc.). Thank you.

**Comment by GabrielBlondeau-Kirby** [comment]
Hi @lahirumaramba 

I'll try to provide you a simple github project asap.

Thank you

**Comment by GabrielBlondeau-Kirby** [comment]
@lahirumaramba Sorry for the delay ...
I created a small project in order to reproduce the bug, unfortunately nothing is going wrong so no `Recursion Error` :thinking: 

We can close the issue for now I guess :( 
Sorry for the trouble...

**Comment by lahirumaramba** [comment]
No problem! I will close this issue for now. We can reopen later if needed.

**Comment by GabrielBlondeau-Kirby** [comment]
The only clue I can give is:
It start working right after I removed the **monkey patch** from Eventlet lib.
> eventlet.monkey_patch(select=False)
