### ISSUE TITLE
Standard library `distutils` module will be removed in Python 3.12

### ISSUE THREAD

**Issue by arsikurin** [firebase/firebase-admin-python#603]
### Description
Standard library `distutils` module is deprecated in Python 3.10 and scheduled for removal in Python 3.12 [(reference)](https://docs.python.org/3.10/whatsnew/3.10.html#distutils).

Importing distutils in Python 3.10 generates the following warning:
```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```
Path to error: `google/cloud/firestore_v1/services/firestore/client.py:17`

### Environment
  * Operating System version: macOS Monterey 12.0.1
  * Firebase SDK version: 5.2.0
  * Firebase Product: database
  * Python version: 3.10.1
  * Pip version: 21.3.1

**Comment by jonathanedey** [comment]
Closing this since it's already been resolved https://github.com/googleapis/google-cloud-python/issues/11977
