### ISSUE TITLE
Requirements for firebase-admin Python in buildozer? 

### ISSUE THREAD

**Issue by CodeWithVallabh** [firebase/firebase-admin-python#604]
I'm developing an app in Python Kivy which uses firebase-admin module also. So, please tell me the requirements needed for firebase-admin to be mentioned in buildozer requirements

Like, ```import requests``` needs
```
requirements = python3,kivy==2.0.0,requests,urllib3,chardet,idna
```
Please help me, I'm searching the firebase-admin buildozer requirements from 10 days.

Thanks in advance

**Comment by lahirumaramba** [comment]
Hi @CodeWithVallabh this is not a platform we officially support so we haven't tested the admin sdk on Python Kivy. However, I found [this on SO](https://stackoverflow.com/a/67813675). See if the [configuration](https://stackoverflow.com/a/67813675) mentioned in the SO answer works for you. In the future, please use StackOverflow for usage questions. Thanks!
