### ISSUE TITLE
Firestore limit_to_last(n) returns the first n elements in a reverse order instead of returning the last n elements

### ISSUE THREAD

**Issue by brenhr** [firebase/firebase-admin-python#605]
### Describe your environment
- SDK version:  5.2.0
- Python version: 3.10.2
- Pip version: 21.2.4
- Firebase product: **Firestore**
### Describe the problem
As per the documentation for [limit_to_last](https://googleapis.dev/python/firestore/latest/query.html#google.cloud.firestore_v1.base_query.BaseQuery.limit_to_last) clause, it should return the last n elements that match the query. However, when executing a simple query (i.e. db.collection("numbers").order_by("number").limit_to_last(5)) it returns the first 5 elements but in a reverse order.
### Steps to reproduce
1. Create a collection and add data (in my case, I created a "numbers" collection, and inserted a total of 50 documents (from number 0 to 49) as follows: 
```
for i in range(50):
    db.collection('numbers').document(f'{i}').set({
        'number': i
    })
```
2. And then, execute the following query and print the results:
```
lastDocs = db.collection('numbers').order_by("number").limit_to_last(5).get()
print('Last docs [using limit_to_last() clause]')

for doc in lastDocs:
    print(f'{doc.to_dict()}')
```

**Expected output:**
```
Last docs [using limit_to_last() clause]
{'number': 45}
{'number': 46}
{'number': 47}
{'number': 48}
{'number': 49}
```

**Real output:**
<img width="810" alt="Screen Shot 2022-02-05 at 19 32 46" src="https://user-images.githubusercontent.com/36976556/152664681-5e3d23f8-9298-491b-9a81-d6aeeb08bdf0.png">

In case you find it useful, I also tried to reproduce this behavior in the [Node.js Admin SDK](https://github.com/firebase/firebase-admin-node), and I obtained the desired output (I mean, `limitToLast()` works perfectly fine):
**Node.js code:**
```
var numbersRef = db.collection("numbers");

console.log("Last documents [using limitToLast()]:");

numbersRef.orderBy("number").limitToLast(5).get().then((snapshot) => {
  snapshot.docs.forEach(doc => {
    console.log(doc.data());
  })
});
```
**Node.js output:**
<img width="793" alt="Screen Shot 2022-02-05 at 19 31 26" src="https://user-images.githubusercontent.com/36976556/152664660-fb76d042-1b96-4714-ac2c-b3972cd229f5.png">

Thanks.

**Comment by lahirumaramba** [comment]
The Admin SDK uses the `google-cloud-firestore` module. Could you ask this issue on the [cloud firestore repo](https://github.com/googleapis/python-firestore), please?
https://github.com/googleapis/python-firestore
