### ISSUE TITLE
Firebase Admin SDK Python throwing error suddenly

### ISSUE THREAD

**Issue by ra1111** [firebase/firebase-admin-python#607]
Trying to Fetch and modify data from the real-time database. No code change was done, working fine till yesterday. 
Tried creating a new key, disabling service, updating packages. Nothing seems to work.

The code is used in Python Firebase Admin SDK. It is used to get and modify data from the real-time database.
I am using firebase_admin to access Firebase Realtime Database.
```
#Add Topics
topics=root.child('Topics/')
Category='Kabaddi'
with open('/Users/user/Desktop/balancerproject/single_sample.json') as response:
    data = json.load(response)
    #topics.update(data)
    topics.child(Category+'/').push(data)
    send_fcm(data)
    #instaQuotes(data.get('Title'))
```
It is throwing error in topics.child(Category+'/').push(data) 

```

TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10bb4b700>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

**Comment by pradyotprksh** [comment]
I also started facing the same issue.

`       
        cred = credentials.Certificate(cert=Constants.Variables.FIREBASE_CRED_FILE_PATH)
        firebase_app = firebase_admin.initialize_app(
            credential=cred,
            name=Constants.Variables.PROJECT_NAME
        )
`

After initialisation I am creating a user,

`
            user = auth.create_user(
                email='user@example.com',
                email_verified=False,
                phone_number='+15555550100',
                password='secretPassword',
                display_name='John Doe',
                photo_url='http://www.example.com/12345678/photo.png',
                disabled=False,
                app=firebase_app
            )
`

Then after sometime I get

`
HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1059edee0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
`

Not sure what is the issue.

**Comment by ra1111** [comment]
> I also started facing the same issue.
> 
> ` cred = credentials.Certificate(cert=Constants.Variables.FIREBASE_CRED_FILE_PATH) firebase_app = firebase_admin.initialize_app( credential=cred, name=Constants.Variables.PROJECT_NAME )`
> 
> After initialisation I am creating a user,
> 
> `user = auth.create_user( email='user@example.com', email_verified=False, phone_number='+15555550100', password='secretPassword', display_name='John Doe', photo_url='http://www.example.com/12345678/photo.png', disabled=False, app=firebase_app )`
> 
> Then after sometime I get
> 
> `HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1059edee0>: Failed to establish a new connection: [Errno 60] Operation timed out'))`
> 
> Not sure what is the cause.

So I figured it out, there was an outage in airtel in India. If you are using airtel try the same with JIO connection, should work.

**Comment by pradyotprksh** [comment]
> > I also started facing the same issue.
> > 
> > ` cred = credentials.Certificate(cert=Constants.Variables.FIREBASE_CRED_FILE_PATH) firebase_app = firebase_admin.initialize_app( credential=cred, name=Constants.Variables.PROJECT_NAME )`
> > 
> > After initialisation I am creating a user,
> > 
> > `user = auth.create_user( email='user@example.com', email_verified=False, phone_number='+15555550100', password='secretPassword', display_name='John Doe', photo_url='http://www.example.com/12345678/photo.png', disabled=False, app=firebase_app )`
> > 
> > Then after sometime I get
> > 
> > `HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1059edee0>: Failed to establish a new connection: [Errno 60] Operation timed out'))`
> > 
> > Not sure what is the cause.
> 
> So I figured it out, there was an outage in airtel in India. If you are using airtel try the same with JIO connection, should work.

I was not on Airtel. I checked my network connection is good. I also made a http request before the firebase call, it worked correctly.
