### ISSUE TITLE
FR: Provide a "Shallow" option when getting data

### ISSUE THREAD

**Issue by grennis** [firebase/firebase-admin-python#61]
Please add support for the [shallow option](https://firebase.google.com/docs/database/rest/retrieve-data#shallow) when retrieving data from the realtime db.

**Comment by giusepperj** [comment]
@hiranya911 When can we expect this to get merged? thank you 😄

**Comment by hiranya911** [comment]
@giusepperj Unfortunately, this PR is broken, and doesn't have any tests. Until those issues are addressed, we cannot make any progress with it. If you or somebody else can put in some time to clean up the code, and provide some tests, I'll be glad to take it to the next stage of the review process.

**Comment by hiranya911** [comment]
I would like to make some progress with this.

@rodolphopivetta will you be able to provide some test cases for us? Otherwise I'll use your PR as a starting point and roll out my own.

**Comment by hiranya911** [comment]
This was released in v2.8.0
