### ISSUE TITLE
[FR] Load GOOGLE_APPLICATION_CREDENTIALS json content via an environment variable instead of a file

### ISSUE THREAD

**Issue by aditdiqdpratama** [firebase/firebase-admin-python#614]
**Is your feature request related to a problem? Please describe.**
i need to load this with env var instead of env var with json file path

**Describe the solution you'd like**
env var instead of file

**Comment by lahirumaramba** [comment]
You should be able to store the json content of your service account in an environment variable, load the content later and create a new `credentials.Certificate` instance in your app. Please note that it might be less secure to store your service account credentials in an environment variable than storing in a file, as anyone (with access) can check the environment of a running process.

```
credential = credentials.Certificate(parsed_json)
app = firebase_admin.initialize_app(cred)
```

**Comment by sjsadowski** [comment]
For future people that show up here, since "parsed_json" is ambiguous - the following works:

```py
import firebase_admin
from firebase_admin import credentials
import json

cred = credentials.Certificate(json.loads(os.getenv("ENV_VAR_NAME")))
firebase_admin.initialize_app(cred)
```
