### ISSUE TITLE
A way to provide clock_skew_in_seconds

### ISSUE THREAD

**Issue by fatadel** [firebase/firebase-admin-python#617]
The method `verify_token` - https://github.com/firebase/firebase-admin-python/blob/6d826fd15c87db62f7501f569b6e0a762d17a05e/firebase_admin/_token_gen.py#L392 - has an additional parameter called `clock_skew_in_seconds` - https://github.com/googleapis/google-auth-library-python/blob/87cd2455aca96ac3fbc4a8b2f8e4c0bba568a70b/google/oauth2/id_token.py#L114.

However, it is not possible to provide this parameter when verifying ID tokens - https://github.com/firebase/firebase-admin-python/blob/6d826fd15c87db62f7501f569b6e0a762d17a05e/firebase_admin/auth.py#L194

I have been recently having issues where validating tokens failed from time to time with a message "Token used too early", where the timestamps were having a difference of 1-3 seconds. I have patched the admin SDK with `clock_skew_in_seconds=10` argument and the issue disappeared. I do understand that my server's time synchronization is the problem in first place but being able to provide existing parameters would also be extremely helpful.

**Comment by Courvoisier13** [comment]
@fatadel could you share how you patched the admin SDK to add `clock_skew_in_seconds=10`?
I am having the same issue.

**Comment by vitorsanc-hu** [comment]
Hi @fatadel, I would really appreciate if you could share how you did it as well, since I'm having the same issue and the Admin SDK seems to not have implemented this yet.

**Comment by jonathanedey** [comment]
Closing this since it was resolved in https://github.com/firebase/firebase-admin-python/pull/714.
