### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by eduardo-bolognini** [firebase/firebase-admin-python#620]
Hi, I don't now how I do to login. I have seek on google documentation but i don't -  find anythink.

Thank you.

**Comment by lahirumaramba** [comment]
Did you mean login as you would log users in using Firebase client SDKs? The Admin SDK is a set of server libraries that lets you interact with Firebase from privilege environments. Please take look at the documentation on how to set it up for Python https://firebase.google.com/docs/admin/setup#python
