### ISSUE TITLE
[FR] Authentication with social media accounts

### ISSUE THREAD

**Issue by oy321** [firebase/firebase-admin-python#630]
**Is your feature request related to a problem? Please describe.**
Is there a way to authenticate users upon registration/login using their social media accounts e.g. Google, FB, Twitter? The firebase doc lists ways using JS etc. but not in Python, and I can't find anything from the firebase admin Python SDK doc neither.

**Describe the solution you'd like**
A feature / function that supports firebase auth with social media accounts.

**Describe alternatives you've considered**
Using a mix of Python and JS scripts if have to..

**Additional context**
N/A

**Comment by lahirumaramba** [comment]
Hey @oy321 , by JS did you mean the Firebase Web SDK? The Firebase Web SDK is a client sdk and supports authenticating users on the client side.
The Firebase Admin SDKs are used on environments with administrative privileges and does not need/support login users.
