### ISSUE TITLE
How to login with email and password in firebase from python using Firebase Admin Python SDK?

### ISSUE THREAD

**Issue by koushikromel** [firebase/firebase-admin-python#641]
This is my first question on GitHub so i thought i should write it as much as detailed if my question was too long kindly excuse me.

I'm using [Pyrebase](https://github.com/thisbejim/Pyrebase)(a third party package to access firebase data) now I'm looking forward to migrate to [Firebase Admin Python SDK](https://github.com/firebase/firebase-admin-python) for all my works i couldn't find this particular thing in firebase-admin 

In [Pyrebase](https://github.com/thisbejim/Pyrebase) i use these commands to create and login to my account using python
To create a new user `auth.create_user_with_email_and_password(email, password)`
To login with email and password `user = auth.sign_in_with_email_and_password(email, password)`

In [Firebase Admin Python SDK](https://github.com/firebase/firebase-admin-python) I can create an auth with create a new user
`firebase_admin.auth.create_user(**kwargs)`  [create user documentation page](https://firebase.google.com/docs/reference/admin/python/firebase_admin.auth#create_user) 
like i do in Pyrebase No issues with this.

But i couldn't find a way to login with password, here it takes email as a parameter and returns the user details
`firebase_admin.auth.get_user_by_email(email, app=None)` [get user documentation page](https://firebase.google.com/docs/reference/admin/python/firebase_admin.auth#get_user)

So my question here is how do i authenticate user by login page by getting user email and password
I wanna know is there any other way to authenticate users in Firebase Admin Python SDK

**Comment by arnavmehta7** [comment]
Hey,
Check below:
`user = auth.create_user_with_email_and_password(email, password)
signin = auth.sign_in_with_email_and_password(email, password)
`

You can sign in with the above

**Comment by lahirumaramba** [comment]
Hi @koushikromel The Admin SDK is used in environments with administrative privileges and login to a user account is not currently a use case that is supported by the SDK. You would want to use one of the Firebase client-side SDKs (iOS, JS, Android etc.) to sign in users from the client side code.

You can use the ID token verification API in the Admin SDK to know what user is signed in on the client side by sending the token from the client to the server and then validating it on the server side. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for more on that.
