### ISSUE TITLE
Real Time Database

### ISSUE THREAD

**Issue by GuilleBarrena** [firebase/firebase-admin-python#65]
Describe your environment

  * Operating System version: Google App Engine (python 2.7 + Flask)
  * Firebase SDK version: latest
  * Library version: _____
  * Firebase Product: database

### [REQUIRED] Step 3: Describe the problem
Hi,

 I have been looking to manage the firebase database from my on backend. My backend is in google app engine, and is running on python 2.7 with Flask. 

Till now I am able to generate a JWT and retrieve it to my app successfully. My next step is to try to push somenthing to the db. For that i am just using your code example in this article:
https://firebase.googleblog.com/2017/07/accessing-database-from-python-admin-sdk.html
but when it reaches the line:
  new_user = root.child('users').push({
    'name' : 'Mary Anning', 
    'since' : 1700
})
it breakes.

Am I doing anything wrong?

pd: Is there any code example in which i can see the correct way of handling errors using the ApiCallError?

Regards,
Guillermo Barrena
#### Steps to reproduce:
Rules:
// These rules require authentication
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}

#### Relevant Code:
```
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db

# This is pointing to the correct place in my aplication
cred = credentials.Cert('path/to/serviceKey.json')
# I have the correct URL in my aplication
firebase_admin.initialize_app(cred, {
    'databaseURL' : 'https://my-db.firebaseio.com'
})

root = db.reference()
# Add a new user under /users.
new_user = root.child('users').push({
    'name' : 'Mary Anning', 
    'since' : 1700
})

```

**Comment by globophobe** [comment]
Have you tried child.set({'user':'data'}) ?

**Comment by hiranya911** [comment]
Your code looks correct. We have an [integration test](https://github.com/firebase/firebase-admin-python/blob/master/integration/test_db.py#L108) which essentially does the same thing, and it works fine. You can verify if it's a problem in the code by saving your code to a standalone Python script, and running it locally. 

Chances are your app is not set up properly for App Engine. Try to get some more information (an error message or a stacktrace) from App Engine logs. Also make sure you have done all the additional steps documented [here](http://google-auth.readthedocs.io/en/latest/user-guide.html#the-app-engine-standard-environment). You need to do all of it, from installing the `requests-toolbelt` library to enabling App Engine billing.

**Comment by hiranya911** [comment]
I'm going to close this, since we haven't from the OP in a while. If the problem still exists, please reopen and provide more details (error logs).
