### ISSUE TITLE
__init__() got an unexpected keyword argument 'notification_count'

### ISSUE THREAD

**Issue by jasmeet-singh-appboxer** [firebase/firebase-admin-python#651]
**My Environment**

  * Operating System version:  macOS Monterey (12.6)
  * Firebase SDK version: 6.0.0
  * Python version: 3.8.14
  * pip version: 22.2.2
  * requests version: 2.28.1
  * urllib3 version: 1.26.12

**Problem Description**

Suppose i have two android devices and if i try to send push notification to both devices:
1. Either one by one: Then first device receive the push notification but Getting error while sending the notification to the second device.
2. Either all at once: Getting error straight away.

**Code**

```python
def send_push_notification(token, data, notification, device_type)
      """
      Send Push Notification on the given firebase token
      :param str token: Firebase Token.
      :param dict data: Extra Data for push notification.
      :param dict notification: default to {"title": "Test Notification", "body": "Lorem Ipsum"}.
      :param str device_type: "ANDROID" in this case.
      """

      message = messaging.Message(
          data=data,
          notification=messaging.Notification(**notification),
          token=token,
      )
      
      if device_type == DeviceType.ANDROID.value[0]:
            notification.update({
                'notification_count': int(data['notification_count'])
                if data.get('notification_count') and data['notification_count'] else None,
            })
      
            message.android = messaging.AndroidConfig(
                data=data,
                notification=messaging.AndroidNotification(**notification)
            )
      
      messaging.send(message)
```

**Comment by lahirumaramba** [comment]
Hi @jasmeet-singh-appboxer it looks like the error message you shared is coming from your code where you try to set an argument (`notification_count`) that is not valid for an object. If you think this is an issue of the SDK, please provide us with a minimal repro or a full working code and we'd be happy to take a look. Thanks!

**Comment by jasmeet-singh-appboxer** [comment]
Hey @lahirumaramba , 
Thanks for the response. But i don't think `notification_count` is an invalid argument, Because as per the official doc it is stated that we can send `notification_count` argument in `AndroidNotification` Function.
Doc: https://firebase.google.com/docs/reference/admin/python/firebase_admin.messaging#androidnotification
