### ISSUE TITLE
WARNING: python3-firebase-admin-6.0.1-r0 do_fetch: Failed to fetch URL https://files.pythonhosted.org/packages/source/f/firebase-admin/firebase-admin-6.0.1.tar.gz, attempting MIRRORS if available

### ISSUE THREAD

**Issue by jahanzaib1234** [firebase/firebase-admin-python#660]
i get this Waring and error when i add firebase-admin package in yocto build 

WARNING: python3-firebase-admin-6.0.1-r0 do_fetch: Failed to fetch URL https://files.pythonhosted.org/packages/source/f/firebase-admin/firebase-admin-6.0.1.tar.gz, attempting MIRRORS if available

**Comment by iyad-salameh** [comment]
version 6 fails to install on raspbian.
i rolled back to 5.4.0 and everything worked

**Comment by lahirumaramba** [comment]
Raspberry Pi is not a platform that we officially support so I am unable to test this. We publish our official distribution artifacts on PyPI. https://pypi.org/project/firebase-admin/
