### ISSUE TITLE
[FR] Add custom timeout to `messaging` methods 

### ISSUE THREAD

**Issue by Tom3652** [firebase/firebase-admin-python#661]
**Is your feature request related to a problem? Please describe.**

I have multiple timeout errors because of my low network connectivity home when trying to use `messaging.send_multicast(message)` to send push notifications.  

**Describe the solution you'd like**

I would like to be able to set a custom timeout to this method to just wait it completes on my server without throwing an error.

**Comment by lahirumaramba** [comment]
Hi @Tom3652 , would the `httpTimeout` in app options help you in this case? https://firebase.google.com/docs/reference/admin/python/firebase_admin#initialize_app

```
app = firebase_admin.initialize_app(
        options={'httpTimeout': CUSTOM_TIMEOUT}
    )
```

**Comment by Tom3652** [comment]
Hi @lahirumaramba, thanks for the option it should actually do the trick ! 
Although i see the default is 2min, it seems more than reasonable so maybe there is an underlying issue with my setup. 

I will anyway set a higher value, if this is used for any firebase admin api it's perfect. 

Regarding this feature request, i think it would be nice anyway to be able to set a custom timeout for HTTP request for different module : we might want a higher timeout for `messaging` than `firestore` for example.

**Comment by lahirumaramba** [comment]
Thank you @Tom3652 . Glad to hear that custom `httpTimeout` works for you in this case. We currently don't have any immediate plans to support custom timeouts per module... however, feel free to submit a separate FR if you think there is a strong use case for such feature. Thanks!
