### ISSUE TITLE
[FR] Count documents with aggregation queries

### ISSUE THREAD

**Issue by BladeRunner713** [firebase/firebase-admin-python#665]
**Is your feature request related to a problem? Please describe.**
It seems like the new count() method mentioned on https://firebase.google.com/docs/firestore/query-data/aggregation-queries has not been implemented in Python SDK. 

**Describe the solution you'd like**
Add the new method so that we can use the count method to count the number of documents in Firestore.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code samples or screenshots about the feature request here.

**Comment by lahirumaramba** [comment]
This is now fixed in https://github.com/firebase/firebase-admin-python/pull/671
We will also update the public docs with code samples. Thanks!
