### ISSUE TITLE
[Documentation] Examples of Authentication with providers

### ISSUE THREAD

**Issue by firemanxbr** [firebase/firebase-admin-python#70]
in the current version I don't find the examples to auth with providers(Google, Facebook, GitHub, etc..). Can create a examples/ in this repo with authentication examples? I can contribute with this ?
My plan is create some examples using firebase-admin library to Python+Flask API. Today don't have these examples with Firebase.

**Comment by katowulf** [comment]
This is not intended to be used as a client library, but instead for privileged admin accounts. To verify clients making requests against your servers, there are a few common practices:

1) Have the client pass their current auth token and use [verify_id_token](https://firebase.google.com/docs/reference/admin/python/firebase_admin.auth#verify_id_token)
2) Have the client write to the Realtime Database and use security rules to verify authentication (don't allow write in not authenticated). Have the server listen on the path for adds and process the requests. (This is a great method for reducing your server stack, see [firebase-queue](https://github.com/firebase/firebase-queue))
3) Utilize [Functions](https://firebase.google.com/docs/functions/), which provide built-in access to user identity in same triggers (e.g. RTDB events).

**Comment by firemanxbr** [comment]
Sorry but my goal is different that you mentioned above. I would like use the firebase as database for my API. I have an API created with Python + Flask + Auth0. In this API we use MongoDB as database. I found some alternatives using JavaScript and Python but this is not a good implementation in my opinion [1]. In that case Firebase  can't used as Database to an API ? I would like use this library but I don't see much advantages in Firebase Auth if I can't use this with Python. My flow followin below:

MongoDB <=> Python API(Auth0) <=> Mobile App IOS/Android and Web. I run all services in GCP. 

I can change from MongoDB and Auth0 to Firebase stack ?

[1] https://github.com/fthai-google/template-app/blob/master/main.py

**Comment by firemanxbr** [comment]
@katowulf your recommendations are JavaScript projects why I'll use JavaScript if have a SDK to Python ? this is a repository to Python not JavaScript if this is don't offer this access from Python maybe the Python community can't use Firebase. Maybe the good alternative is continue using the Auth0 service and MongoDB.

**Comment by firemanxbr** [comment]
@hiranya911 What are goal of this SDK if don't offer the same features of Node.JS and Go SDK ? I would like use Firebase in my Python APIs because have the Authentication and Database in the same service. Do you can provide any example or explain more. I'll create a post my blog about this SDK if works like Node and Go.

**Comment by hiranya911** [comment]
@katowulf is right. The Admin SDKs do not support authenticating as end users (this is same across all languages we support; Node and Go don't support it either). The Admin SDKs should only be used in privileged environments, and therefore supports authenticating with service accounts and other types of Google Cloud credentials.

However, you claim that your workflow is something like the following:

```
MongoDB <=> Python API(Auth0) <=> Mobile App IOS/Android and Web. I run all services in GCP.
```

Now this is something Admin SDK supports. But you need to do the end user authentication in your mobile or web app, and pass the resulting ID token to the Python service. There, the admin SDK can call `verify_id_token()` (as @katowulf mentioned), and then you can proceed to access the database on behalf of the user.

**Comment by firemanxbr** [comment]
Perfect. Thanks for explain the flow recommended. I'll implement and test. Have a good one.
