### ISSUE TITLE
[FR] Add multiple Firestore support

### ISSUE THREAD

**Issue by KSokhal** [firebase/firebase-admin-python#718]
**Is your feature request related to a problem? Please describe.**
I have a Firebase project that utilised the recent feature to allow for multiple Firestores for a single project and am using Python to perform some firebase admin function, but it currently doesn't allow access to any non-default databases.

**Describe the solution you'd like**
I would like to be able to specify which Firestore to connect to when initializing the connection.

**Describe alternatives you've considered**
Cannot find any alternative to this feature with this package. The only other alternative would be to use Node.js SDK instead since it does have this feature.

**Comment by liamvdv** [comment]
Update?

**Comment by juansep17** [comment]
Hello, are you working on this?
