### ISSUE TITLE
Transaction contextmanager does not set transaction to in_progress

### ISSUE THREAD

**Issue by thunderbug1** [firebase/firebase-admin-python#735]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: docker image  tiangolo/uvicorn-gunicorn-fastapi:python3.10
  * Firebase SDK version: 6.2.0
  * Firebase Product: firebase_admin (auth, database, storage, etc)
  * Python version: 3.10
  * Pip version: 22.0.2

#### Steps to reproduce:

Use transaction context manager in fastapi endpoint and run code in cloud run.

#### Relevant Code:

```
from firebase_admin import firestore
db = firestore.client()
```

the context manager for transactions does not properly work:

```
with db.transaction() as transaction:
        logging.info(f"transaction.in_progress: {transaction.in_progress}") -> prints false
```

this works on the other hand:
```
transaction = db.transaction()
@firestore.transactional
def do_work(transaction):
    logging.info(f"transaction.in_progress: {transaction.in_progress}") -> prints true
do_work(transaction)
```

**Comment by lahirumaramba** [comment]
Hey @thunderbug1, it looks like this issue pertains to __Cloud Firestore__. Please report directly in the
[Python Firestore](https://github.com/googleapis/python-firestore) GitHub repo so the right teams can investigate it.
