### ISSUE TITLE
document mandatory appengine configuration in Firebase docs

### ISSUE THREAD

**Issue by ncouture** [firebase/firebase-admin-python#74]
For the record, this is a traceback from using firebase_adm pyhon sdk on appengine standard with 3rd party libraries google-oauth, and custom oauth2client, amongst others:

```
Environment:


Request Method: GET
Request URL: <redacted>

Django Version: 1.11.3
Python Version: 2.7.12
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
  [...])

Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'house.middleware.OAuth2TokenMiddleware')



Traceback:

[...]

File "/base/data/home/apps/[...]/models.py" in user_created_callback
  82.     uid = create_firebase_user_from_google_signin(google_user)

File "/base/data/home/apps/s~[...]/models.py" in create_firebase_user_from_google_signin
  53.         disabled=False)

File "/base/data/home/apps/[...]/v1.404130886528581043/lib/firebase_admin/auth.py" in create_user
  194.         uid = user_manager.create_user(**kwargs)

File "/base/data/home/apps/[...]/v1.404130886528581043/lib/firebase_admin/_user_mgt.py" in create_user
  215.             response = self._request('post', 'signupNewUser', json=payload)

File "/base/data/home/apps/s~[...]/v1.404130886528581043/lib/firebase_admin/_user_mgt.py" in _request
  306.         resp = self._session.request(method, ID_TOOLKIT_URL + urlpath, **kwargs)

File "/base/data/home/apps/[...]/v1.404130886528581043/lib/google/auth/transport/requests.py" in request
  176.             self._auth_request, method, url, request_headers)

File "/base/data/home/apps/[...]/v1.404130886528581043/lib/google/auth/credentials.py" in before_request
  121.             self.refresh(request)

File "/base/data/home/apps/[...]/v1.404130886528581043/lib/google/oauth2/service_account.py" in refresh
  322.             request, self._token_uri, assertion)

File "/base/data/home/apps/[...]/v1.404130886528581043/lib/google/oauth2/_client.py" in jwt_grant
  143.     response_data = _token_endpoint_request(request, token_uri, body)

File "/base/data/home/apps/s[...]/v1.404130886528581043/lib/google/oauth2/_client.py" in _token_endpoint_request
  104.         method='POST', url=token_uri, headers=headers, body=body)

File "/base/data/home/apps/[...]/v1.404130886528581043/lib/google/auth/transport/requests.py" in __call__
  115.             raise exceptions.TransportError(exc)

Exception Type: TransportError at /oauth2/oauth2callback/
Exception Value: ('Connection broken: IncompleteRead(93 bytes read)', IncompleteRead(93 bytes read))
```

This issue is quickly resolved by following the google-oauth app engine standard-specific installation instructions, notably the addition of the environment variable `GAE_USE_SOCKETS_HTTPLIB` in app.yaml as follows:
```
GAE_USE_SOCKETS_HTTPLIB: 'true'
```

as per https://google-auth.readthedocs.io/en/latest/user-guide.html#the-app-engine-standard-environment.

Since this library is a dependency of firebase-admin-python, would it be appropriate to add a note as to this required configuration in README.md? The reason I am asking is because the traceback is not very descriptive as to what might be causing this and it is currently hard to find the information necessary to make this work.

@salqadri now that I read the library is tested on app engine it makes me think this could be due to something specific to my environment--where can we see how the library is tested on app engine (README.md), if not is this a known quirk?

**Comment by hiranya911** [comment]
The additional steps for setting up the `google-auth` library in App Engine are always required when deploying to GAE. I [wrote those steps](https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/172) after testing with Python Admin SDK. GAE also provides some [documentation](https://cloud.google.com/appengine/docs/standard/python/issue-requests) on these requirements, but I personally found their docs a little confusing. 

I think it's probably a good idea to add a link to the additional steps somewhere in Firebase devsite, rather than here in the README.

**Comment by hiranya911** [comment]
@egilmorez can we find a suitable place in Admin SDK documentation for this information?

**Comment by egilmorez** [comment]
Added a link and note adjacent to the code snippet for initializing the Python Admin SDK:

"To use the Python Admin SDK in the Google App Engine standard environment, you'll need some extra configuration."

Brief, but I hope it will help Python users find the required information.

**Comment by hiranya911** [comment]
This is live at https://firebase.google.com/docs/admin/setup

Thanks @egilmorez
