### ISSUE TITLE
Github Desktop Pull/Push Issue

### ISSUE THREAD

**Issue by gosala** [firebase/firebase-admin-python#746]
**I got this issue suddenly when push code into server from GitHub desktop**
`(fatal: unable to access 'https://github.com/xxxxx.git/': schannel: AcquireCredentialsHandle failed: SEC_E_INTERNAL_ERROR (0x80090304) - The Local Security Authority cannot be contacted)`

i **tried to clear the cache and reinstall also still the issue same.**
please help me out

**Comment by lahirumaramba** [comment]
This repository is for Firebase Admin Python SDK issues. Looks like what you have reported is a github tools related issue.
