### ISSUE TITLE
[FR] Adding global var

### ISSUE THREAD

**Issue by EhyMaik97** [firebase/firebase-admin-python#755]
I'm always frustrated when I see line repeated. In the /snippets/database/index.py there are 4 times the string "https://databaseName.firebaseio.com"

I want to substitute four equals string with an env var like DB_URL and insert the string above, so in this way the user have to edit it only 1 time

**Comment by EhyMaik97** [comment]
Can you assign to me?

**Comment by Gbirla06** [comment]
Is it still pending ?

**Comment by jonathanedey** [comment]
Hi @EhyMaik97 and @Gbirla06, Thanks for your interest here. These code snippets are used for reference documentation purposes so I think we should leave them as is. Closing this and the related PR.
