### ISSUE TITLE
Update only if etag is unchanged. 

### ISSUE THREAD

**Issue by alexanderwhatley** [firebase/firebase-admin-python#77]
Right now there does not seem to be an easy solution to the transaction operation if I have a previous value for an ETag, and I want to update the corresponding part of the database only if the ETag is the same (note that set_if_unchanged is not sufficient because this is an update operation). Should we perhaps add an "update_if_unchanged" operation or something else?

**Comment by hiranya911** [comment]
Just to make sure I understood correct, how would it be different from the existing `transaction()` or `set_if_unchanged()` methods? By performing an update instead of a full overwrite (HTTP PATCH as opposed to PUT)?

Not sure if the server API supports that kind of an operation. @caseycrogers, does this sound like something we can do?

**Comment by alexanderwhatley** [comment]
Hi Hiranya, I don't think that either of those methods suffice here, since
the transaction() method is rather rudimentary and high level, and the
set_if_unchanged method does the set operation, not the update operation.
On second thought, I think it makes the most sense here to bring back the
etag() method. To do the task I described, I could call the etag() method
at the beginning, then call it right before the update, and if the etags
match, then continue with the update operation. What do you think?
ᐧ

**Comment by hiranya911** [comment]
I'm not convinced that this can be implemented without server-side support. For instance suppose you do:

```
data, etag = ref.get(etag=True)
make_changes_to(data)
if etag ==  ref.etag():
  # Foo
  ref.update(data)
```

If another client updates data in the server at `#Foo`, we will overwrite the change leading to the lost-update problem. We need an atomic, server-supported update-if-unchanged operation for this.

**Comment by alexanderwhatley** [comment]
@hiranya911, any updates on this? Also, is there documentation about how transactions are done in the new Firestore database? I wasn't able to find anything. Thanks.

**Comment by rockwotj** [comment]
Sorry I missed this. What you do you by update-if-unchanged? You want to two 2 writes and make sure no data is changed inbetween them you just need to set the same `'X-Firebase-ETag: true'` header in the write and you'll get the ETag back just if you did a read there right after the operation is done. You can use that etag in the next write.

As for Firestore transactions, here are the python docs (which I guess that's what you want): https://googlecloudplatform.github.io/google-cloud-python/latest/firestore/transaction.html

Firestore transactions are much more powerful and let you do full read/write operations atomically.

**Comment by hiranya911** [comment]
Hi @rockwotj. The SDK currently supports a [`set_if_unchanged()`](https://firebase.google.com/docs/reference/admin/python/firebase_admin.db#reference) method which handles this. I guess the question is can we support a similar `update_if_unchanged()` method. In REST terms can we do a conditional `PATCH` request?

**Comment by rockwotj** [comment]
Yeah you can do it with `PATCH` too

**Comment by hiranya911** [comment]
Thanks @rockwotj.

@alexanderwhatley Would you be interested in providing us a PR? I assume it will be very similar to the existing `set_if_unchanged()`, except using HTTP `patch` method instead of `put`.

**Comment by alexanderwhatley** [comment]
Sure @hiranya911, I'll get something up by tomorrow hopefully.

**Comment by hiranya911** [comment]
And on a tangential, Firestore support for Python admin SDK is being developed at #79.

**Comment by caseycrogers** [comment]
A quick correction, none of the conditional request features (ie ETags, if-none-match) are supported with the PATCH method.
This is because, with PATCH, it's unclear what should be used to compute the ETag.

I'm not entirely sure what you mean by "set" vs. "update". Do you mean "PUT" vs. "PATCH"?

**Comment by hiranya911** [comment]
Oh! I was afraid of this.

And just to clarify @caseycrogers, you're right.
* set = PUT = total overwrite
* update = PATCH = selective update of children

The problem with implementing `update_if_unchanged()` as a series of PUT operations is, then it is no longer atomic.  I think @alexanderwhatley is trying to read a parent object along with its etag, and then atomically update some of its children. Something like:

```
data, etag = ref.get(etag=True)
update = {'foo' : 'bar', 'baz' : data.get('baz') + 1}
ref.update_if_unchanged(update, etag) # This should ideally be a single REST call
```

**Comment by caseycrogers** [comment]
@alexanderwhatley can we get some more context as to what you are trying to achieve? There might be some easy ways to rewrite your code not to depend on patch depending on how your data is structured and what exactly you are trying to achieve.

**Comment by alexanderwhatley** [comment]
@caseycrogers, I am trying to do what hiranya is saying, which doesn't appear possible right now. I most likely will just switch to using Firestore anyways, which appears to support this kind of transaction, so this should be a nonissue.

**Comment by caseycrogers** [comment]
What solution will work best for you will depend heavily on your data structure. It may be that the Database's transactions implementation will suite your needs well without the need for an update or PATCH.

However, as you said, this may be a non-issue given that Firestore's conditional requests support this. Let me know if you decide to proceed with this in the Database.

**Comment by hiranya911** [comment]
I'm closing this since the backend API doesn't seem to support this. We can revisit this if this turns out to be a critical use case.
