### ISSUE TITLE
Couldn't import app_check

### ISSUE THREAD

**Issue by karambaq** [firebase/firebase-admin-python#773]
* Operating System version: macOS Sonoma 14.0
  * Firebase SDK version: 5.4.0
  * Firebase Product: ?
  * Python version: 3.11
  * Pip version: 23.3.2

### [REQUIRED] Step 3: Describe the problem
Error while importing `app_check` as in documentation
https://firebase.google.com/docs/app-check/custom-resource-backend

#### Steps to reproduce:

```
pip install firebase_admin

python -c "import firebase_admin; from firebase_admin import app_check"
```

ERROR:

```python
ImportError: cannot import name 'app_check' from 'firebase_admin'
```
#### Relevant Code:

```
import firebase_admin
from firebase_admin import app_check
```

**Comment by jonathanedey** [comment]
Hi @karambaq, App Check support was only added in [v6.0.0](https://github.com/firebase/firebase-admin-python/releases/tag/v6.0.0). Please update to a newer version to resolve your issue.
