### ISSUE TITLE
Cloud run from gcp console

### ISSUE THREAD

**Issue by atom2-source** [firebase/firebase-admin-python#787]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a GitHub issue.
  * If the issue pertains to __Cloud Firestore__, report directly in the
    [Python Firestore](https://github.com/googleapis/python-firestore) GitHub repo. Firestore
    bugs reported in this repo will be closed with a reference to the Python Firestore
    project.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)
  * Python version: _____
  * Pip version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
Might just use the moderated images example from the repo and keep them on firebase until i figure out a reliable way to move between firebase and gcp.was using the function to move the images from users out of fire storage to my regular google storage as the firebase is the only public access point as there created for cloud vision but it wasn't working .

**Comment by lahirumaramba** [comment]
Closing due to lack of information
