### ISSUE TITLE
verify_token() got an unexpected keyword argument 'clock_skew_in_seconds'

### ISSUE THREAD

**Issue by minhyung-joo** [firebase/firebase-admin-python#795]
* Operating System version: Sonoma 14.5
  * Firebase SDK version: 6.5.0
  * Firebase Product: auth
  * Python version: 3.9.12
  * Pip version: 21.2.4

I'm using `firebase_auth: ^5.1.0` and `await FirebaseAuth.instance.signInWithProvider(appleProvider);` to authenticate the user on frontend and sending the id token to the server to verify it. On the server side, when running `auth.verify_id_token(token)` I'm suddenly getting this error message: `verify_token() got an unexpected keyword argument 'clock_skew_in_seconds'`

I haven't changed any auth-related code in both frontend and backend, so I have no idea how to even proceed in fixing this issue. It just started showing this error since yesterday. Let me know if I need to provide more information.

**Comment by ur-uw** [comment]
Did you fix that? same issue is present here with python backend
