### ISSUE TITLE
Issue with send_all Function: Messages Not Delivered to Any Tokens on September 12

### ISSUE THREAD

**Issue by YuseongJay** [firebase/firebase-admin-python#811]
### [READ] Step 1: Are you in the right place?

Issue Summary: When sending FCM messages using the send_all function, as of September 12, some tokens are not receiving the messages. I couldn't find any indication in the Python SDK documentation that send_all is deprecated. What could be the issue?

### [REQUIRED] Step 2: Describe your environment
  * Operating System version: Amazon Linux 2023
  * Firebase SDK version: 5.4.0 and 6.5.0
  * Firebase Product: Messaging (FCM)
  * Python version: 3.9.16
  * Pip version: 21.3.1

#### Steps to reproduce:

When attempting to send FCM messages to multiple tokens using the send_all function, some tokens are not receiving the messages. The issue started on September 12, and there was no indication in the Python SDK documentation that this function is deprecated. Could you help identify the cause of the message delivery failure?

#### Relevant Code:
```
from firebase_admin import messaging

# Example code
messages = [
    messaging.Message(token=token1),
    messaging.Message(token=token2),
    # Add more messages
]

response = messaging.send_all(messages)
print('Successfully sent message:', response)
```

**Comment by trinity31** [comment]
I have the same problem when sending multicast message using

message = messaging.MulticastMessage(
                notification=messaging.Notification(
                    title=message_title,
                    body=message_body,
                ),
                tokens=registration_tokens,
            )

exception:
Operation is not implemented, or supported, or enabled.

**Comment by loekTheDreamer** [comment]
google reinvents bullet time, messages never hit anyone...

**Comment by Awethentique** [comment]
Just like Neo in 'The Matrix', it seems like the FCM messages are dodging the intended recipients. 💡💻 Perhaps it's time to don a black trench coat and sunglasses to crack this case like Trinity and Morpheus. 🕵️👀

**Comment by taehyongi** [comment]
I also checked because push notifications are not working.
messaging.send works
messaging.send_multicast does not work.
What is the problem?

**Comment by domag0j** [comment]
messaging.send_all uses https://fcm.googleapis.com/batch endpoint which is deprecated. 
 please see :  https://firebase.google.com/support/faq#fcm-23-deprecation 

we replaced it with messaging.send_batch which uses new v1 FCM API which works OK.

**Comment by kebenxiaoming** [comment]
messaging.send_each_for_multicast
This method can work

**Comment by lahirumaramba** [comment]
Hey folks, `send_all()` and `send_multicast()` APIs were [deprecated](https://firebase.google.com/support/release-notes/admin/python#version_620_-_22_june_2023) in `v6.2.0`.
Use `send_each()` and `send_each_for_multicast()` APIs instead.
