### ISSUE TITLE
iOS devices never receive data-only message

### ISSUE THREAD

**Issue by Pedrozena** [firebase/firebase-admin-python#815]
### Describe your environment

  * Operating System version: Amazon Linux 2 (AWS Lambda)
  * Firebase SDK version: 6.5.0
  * Firebase Product: messaging
  * Python version: 3.10
  * Pip version: _____

### Describe the problem

I'm having the same problem reported here https://stackoverflow.com/questions/69244666/flutter-with-firebase-messaging-ios-device-doesnt-receive-data-only-messages
Since the question in unanswered for 3 years, I guess it's fine to open an issue here.

Android devices receive data-only messages, while iOS ones receive regular messages with `non-null` notifications.
While using legacy FCM api with the following payload:
```
{
  "to": token,
  "priority": "high",
  "content_available": true,
  "data": {
    "new_message": {
      "sender_uid": sender_uid,
      "message_payload": message,
    },
  },
}
 ```
 iOS devices regularly receive also data-only messages.

#### Steps to reproduce:

I'm sending messages to my devices with the following code:

```
from firebase_admin import messaging

def send_message_to_token(token, notification=None):
    data = {"foo": "bar"}
    apns = None
    android = None
    if notification is None:
        apns = messaging.APNSConfig(
            payload=messaging.APNSPayload(
                aps=messaging.Aps(content_available=True, custom_data={"gcm.message_id": str(uuid.uuid4())})
            )
        )
        android = messaging.AndroidConfig(priority="high")
    else:
        notification = messaging.Notification(**notification)
    message = messaging.Message(data, notification=notification, token=token, apns=apns, android=android)
    messaging.send(message, app=get_app())
```

**Comment by chong-shao** [comment]
For the request to the v1 API, have you tried to set content_available to a numeric value? https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html

**Comment by Pedrozena** [comment]
Hi @chong-shao. The payload is parsed and formatted from the sdk.
The resolved payload sent [here](https://github.com/firebase/firebase-admin-python/blob/c0447297d5f1020d7f82e3d0f50e6220babd9b07/firebase_admin/messaging.py#L411) is the following:
```
{
    "android": {
        "priority": "high"
    },
    "apns": {
        "payload": {
            "aps": {
                "content-available": 1
            }
        }
    },
    "data": {
       ...
    },
    "topic": "..."
}
```

**Comment by chong-shao** [comment]
Hi @Pedrozena , thanks for confirming the correctness of the payload. To further help on this issue, I'd suggest reaching out to Firebase Support https://firebase.google.com/support where you can provide your identifiers for debugging.
