### ISSUE TITLE
Error on installation from github URL

### ISSUE THREAD

**Issue by rodolphopivetta** [firebase/firebase-admin-python#84]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 16.04.3 LTS 
  * Firebase SDK version: 2.4.0
  * Library version: 
  * Firebase Product: 

### [REQUIRED] Step 3: Describe the problem

I'm trying to install firebase-admin-python from github URL (I actually want to install my fork), but the setup.py file imports project before dependencies instalations, and this causes an import error.

#### Steps to reproduce:

```
$ pip install -e git+https://github.com/firebase/firebase-admin-python.git#egg=firebase-admin-python
Obtaining firebase-admin-python from git+https://github.com/firebase/firebase-admin-python.git#egg=firebase-admin-python
  Updating /tmp/.venv/src/firebase-admin-python clone
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/.venv/src/firebase-admin-python/setup.py", line 24, in <module>
        import firebase_admin
      File "/tmp/.venv/src/firebase-admin-python/firebase_admin/__init__.py", line 20, in <module>
        import six
    ImportError: No module named 'six'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/.venv/src/firebase-admin-python/
```

On my local I removed the `import firebase_admin` ([link](https://github.com/firebase/firebase-admin-python/blob/master/setup.py#L24)) and replaces `__version__` value with the version string. It works.

I'm not sure how this can work in pypi but not in local.

**Comment by hiranya911** [comment]
This is not something we are interested in supporting. We need the `setup.py` file as it is for out release pipeline to work. If you wish to install from Github:

1. Clone the repo
2. Install the dependencies (`pip install -r firebase-admin-python/requirements.txt`)
3. Install `firebase_admin` from the directory (`pip install -e firebase-admin-python`)
