### ISSUE TITLE
Unable to query by boolean False

### ISSUE THREAD

**Issue by arichen** [firebase/firebase-admin-python#88]
* Operating System version: OSX 10.11.4
  * Firebase SDK version: Firebase Admin Python SDK 2.4.0
  * Firebase Product: database

In firebase-admin-python/firebase_admin/db.py , it's unable to use equal_to(), start_at(), and end_at() with a boolean False value. It throws `ValueError: Equal to value must not be empty or None.`

Suggest the condition of False boolean value to be catered.

**Comment by andremoniz** [comment]
Hi @hiranya911 do you know when this fix will be release?

**Comment by hiranya911** [comment]
@andremoniz Planning a patch release later this week.
