### ISSUE TITLE
GAE_USE_SOCKETS_HTTPLIB interferes with Google Api Python Client

### ISSUE THREAD

**Issue by giusepperj** [firebase/firebase-admin-python#93]
* Operating System version: OSX 10.12.6
  * Firebase SDK version: Firebase Admin Python SDK 2.4.0

When using the SDK within an App Engine environment, the docs require you do some [extra configuration](https://google-auth.readthedocs.io/en/latest/user-guide.html#the-app-engine-standard-environment). Within that configuration you have to add the following variables to your app.yaml

```yaml
libraries:
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'true'
```
However, this introduces an error within app engine that breaks any requests that have to do with the [google api python client library](https://github.com/google/google-api-python-client). Through some research I found [this](https://stackoverflow.com/questions/31066876/why-does-using-the-google-apis-python-client-in-appengine-with-gae-use-sockets-h) question that explains my issue.

Is there a workaround that permits the use GAE_USE_SOCKETS_HTTPLIB in order for firebase to function properly as well as being able to use google api client library within app engine such as:

```python
from apiclient.discovery import build
service = build('calendar', 'v3')
# etc...
```

I am fairly new to python, I apologize if this questions seems out of place.

Thank you in advance for you feedback.

**Comment by hiranya911** [comment]
According to the issue you've linked, the solution is to enable billing for the project (which is required anyway when using sockets). Have you enabled billing?

**Comment by giusepperj** [comment]
Yes, I did enable up billing.

I set up a very minimal proof of error in this repository: https://github.com/giusepperj/firebase_youtube

**Comment by hiranya911** [comment]
Thanks for the repro. After trying several workarounds it doesn't look like we can do anything in the Admin SDK end to alleviate this problem. I even tried calling the Youtube API client via the [google-auth-library-python-httplib2](https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2) library, and got the same error.

As far as I can see, the call to Realtime Database works both with and without the environment variable. Therefore I think your options are:

1. Test the app without the environment variable. I can confirm that the database call works in the dev server without it. Chances are it will work in the prod environment as well. You might see a warning, but you can ignore it.

```
~/firebase_youtube/lib/urllib3/contrib/appengine.py:115: AppEnginePlatformWarning: urllib3 is using URLFetch on Google App Engine sandbox instead of sockets. To use sockets directly instead of URLFetch see https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html.
  AppEnginePlatformWarning)
WARNING  2017-11-11 00:04:20,419 urlfetch_stub.py:551] Stripped prohibited headers from URLFetch request: ['Content-Length']
 {u'h': {u'j': u'j47', u'k': u'k47', u'i': u'i47'}, u'bar': 1510341120447}
```

2. If the app doesn't work in the prod environment without the environment variable, you should file a bug against the Google API client. Socket API is an officially [supported](https://cloud.google.com/appengine/docs/standard/python/sockets/#making_httplib_use_sockets) feature of App Engine, and the library should support it.

**Comment by giusepperj** [comment]
Removing the environment variable did the trick for both development and production. Thank you so much for your help and the detailed explanation @hiranya911

**Comment by hiranya911** [comment]
Thanks @giusepperj. I will update our documentation, so that step is no longer mentioned as required.
