### ISSUE TITLE
ValueError: Invalid service account certificate. Certificate must contain a "type" field set to "service_account".

### ISSUE THREAD

**Issue by jesusignazio** [firebase/firebase-admin-python#94]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Arch Linux kernel 4.13.11-1-ARCH
  * Firebase SDK version: 2.5.0
  * Library version: 2.50
  * Firebase Product: database 

#### Steps to reproduce:

I downloaded the default google-services.json file from my project's Firebase console.

Then I have the following error:

`ValueError: Invalid service account certificate. Certificate must contain a "type" field set to "service_account".`

#### Relevant Code:

```
import firebase_admin
from firebase_admin import db
from firebase_admin import credentials

cred = credentials.Certificate('google-services.json')
firebase_admin.initialize_app(cred)
```

**Comment by hiranya911** [comment]
The error message states what the problem is. `google-services.json` is not a service account certificate. You have to download the service account certificate by going to the `Settings >  Service Accounts` tab, and then clicking on the `Generate New Private Key` button.

https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app
