### ISSUE TITLE
Handling Errors in python

### ISSUE THREAD

**Issue by harpangell7** [firebase/firebase-admin-python#99]
What is the correct way to handle this error? I've created two stack questions and both answers no longer work. Here is my code:

```
from firebase_admin import auth as admin_auth

try:
    uid = 'testUID'
    email = 'test@test.com' # test@test.com already exists
    admin_auth.update_user(uid, email=email)
except Exception as e:
    print(e)
```

I get the following response:

`Failed to update user: testUID.
Server response: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "EMAIL_EXISTS"
   }
  ],
  "code": 400,
  "message": "EMAIL_EXISTS"
 }
}
`

Am I creating the exception correctly? If I use:

`except ValueError as e:`

I get the response in a string. What I want is to get the status and message.

**Comment by hiranya911** [comment]
@harpangell7 You should catch [`auth.AuthError`](https://firebase.google.com/docs/reference/admin/python/firebase_admin.auth#autherror).

```
try:
    uid = 'testUID'
    email = 'test@test.com' # test@test.com already exists
    admin_auth.update_user(uid, email=email)
except auth.AuthError as e:
    cause = e.detail # cause is of type _user_mgt.ApiCallError
    cause = cause.detail # cause is of type requests.exceptions.RequestException
```

`RequestException` is the low-level HTTP error raised by the `requests` library. You should be able to access the HTTP response, status code and the JSON payload via that. Here's how we do that in the SDK: https://github.com/firebase/firebase-admin-python/blob/master/firebase_admin/_user_mgt.py#L267
